### ISSUE TITLE
CD Artifactory secrets not creating for openshift-token-kubernetes-credentials

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#2781]
### Service

trusted.ci.jenkins.io

### Summary

Details:
- It failed at least the last 2 runs
- It has never worked before
- It's the only one failing with this error
- PR https://github.com/jenkins-infra/repository-permissions-updater/pull/2383
- It's failing at artifactory to create the secret
- username appears to be 64 chars long `CD-for-jenkinsci__openshift-token-kubernetes-credentials-plugin`
- maybe this is related although it does say it's fixed: https://www.jfrog.com/jira/browse/RTFACT-26173

cc @daniel-beck / @jglick

Log from trusted ci:

```
03:40:41  2022-02-16 03:40:41.570+0000 [id=1]	INFO	java_util_logging_Logger$log$1#call: Generating token with request payload: username=CD-for-jenkinsci__openshift-token-kubernetes-credentials-plugin&scope=member-of-groups%3Areaders%2Cgeneratedv2-cd-jenkinsci_openshift-token-kubernetes-cr_336273c&expires_in=14400
03:40:41  2022-02-16 03:40:41.915+0000 [id=1]	INFO	o.c.g.r.c.PlainObjectMetaMethodSite#doInvoke: POST request to https://repo.jenkins-ci.org/api/security/token returned error: HTTP 400 Bad Request
03:40:41  2022-02-16 03:40:41.915+0000 [id=1]	WARNING	o.c.g.r.c.PlainObjectMetaMethodSite#doInvoke: Failed to generate token for jenkinsci/openshift-token-kubernetes-credentials-plugin
03:40:41  java.io.IOException: Server returned HTTP response code: 400 for URL: https://repo.jenkins-ci.org/api/security/token
03:40:41  	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
03:40:41  	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
03:40:41  	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
03:40:41  	at java.base/jdk.internal.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
03:40:41  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:40:41  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
03:40:41  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
03:40:41  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
03:40:41  	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351)
03:40:41  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64)
03:40:41  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:160)
03:40:41  	at io.jenkins.infra.repository_permissions_updater.ArtifactoryAPI$ArtifactoryImpl$_generateTokenForGroup_closure2.doCall(ArtifactoryAPI.groovy:230)
03:40:41  	at io.jenkins.infra.repository_permissions_updater.ArtifactoryAPI$ArtifactoryImpl$_generateTokenForGroup_closure2.doCall(ArtifactoryAPI.groovy)
03:40:41  	at jdk.internal.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
03:40:41  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:40:41  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
03:40:41  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
03:40:41  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
03:40:41  	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
03:40:41  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
03:40:41  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:37)
03:40:41  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
03:40:41  	at io.jenkins.infra.repository_permissions_updater.ArtifactoryAPI$ArtifactoryImpl$__clinit__closure1.doCall(ArtifactoryAPI.groovy:291)
03:40:41  	at jdk.internal.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
03:40:41  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:40:41  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
03:40:41  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
03:40:41  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
03:40:41  	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
03:40:41  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
03:40:41  	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011)
03:40:41  	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994)
03:40:41  	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:180)
03:40:41  	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeClosure(ScriptBytecodeAdapter.java:586)
03:40:41  	at io.jenkins.infra.repository_permissions_updater.ArtifactoryAPI$ArtifactoryImpl.generateTokenForGroup(ArtifactoryAPI.groovy:218)
03:40:41  	at jdk.internal.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
03:40:41  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:40:41  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
03:40:41  	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
03:40:41  	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
03:40:41  	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:70)
03:40:41  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:143)
03:40:41  	at io.jenkins.infra.repository_permissions_updater.ArtifactoryPermissionsUpdater$_generateTokens_closure8.doCall(ArtifactoryPermissionsUpdater.groovy:416)
03:40:41  	at jdk.internal.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
03:40:41  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:40:41  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
03:40:41  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
03:40:41  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
03:40:41  	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
03:40:41  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
03:40:41  	at groovy.lang.Closure.call(Closure.java:405)
03:40:41  	at groovy.lang.Closure.call(Closure.java:421)
03:40:41  	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2331)
03:40:41  	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2316)
03:40:41  	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2357)
03:40:41  	at org.codehaus.groovy.runtime.dgm$186.invoke(Unknown Source)
03:40:41  	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:244)
03:40:41  	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
03:40:41  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
03:40:41  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
03:40:41  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
03:40:41  	at io.jenkins.infra.repository_permissions_updater.ArtifactoryPermissionsUpdater.generateTokens(ArtifactoryPermissionsUpdater.groovy:405)
03:40:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:40:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
03:40:41  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:40:41  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
03:40:41  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
03:40:41  	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:149)
03:40:41  	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:100)
03:40:41  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
03:40:41  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:196)
03:40:41  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:208)
03:40:41  	at io.jenkins.infra.repository_permissions_updater.ArtifactoryPermissionsUpdater.main(ArtifactoryPermissionsUpdater.groovy:471)
```

**Comment by timja** [comment]
@jonesbusy you could try shortening the length of your github repo? Maybe removing `token` from the name?

**Comment by daniel-beck** [comment]
We could shorten the generated part of the name some (e.g. remove `-for` or just one underscore), but all that does is kicking the can down the road. We already need to limit artifact ID length per https://github.com/jenkins-infra/update-center2/pull/551#issuecomment-955194014 and it looks like 45 chars for the name is overly generous once CD is involved, so I guess the limit for that is _63 ≥ `CD-for-jenkinsci__-plugin` + artifact ID_, i.e. 38?

Rather than just change the repo name, since the plugin has never been released, we should adapt the plugin ID likewise.

**Comment by jonesbusy** [comment]
I will rename the repo and artifact ID to not exceed maximum length

Thanks

**Comment by jonesbusy** [comment]
After shortening the name of repo and artifact ID, secrets are created successfully

![token_repo_length](https://user-images.githubusercontent.com/825750/154429715-a7775444-bb11-4fe6-ac19-c77a5407d647.PNG)
