### ISSUE TITLE
Invalid sendgrid configuration on trusted.ci

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/helpdesk#2856]
### Service(s)

trusted.ci.jenkins.io

### Summary

trusted.ci has sendgrid configured for email notifications. This configuration appears to be wrong and should be fixed or removed.

I recently saw a build log with the following:

```
00:03:09.400  javax.mail.AuthenticationFailedException: 535 Authentication failed: Basic authentication is not allowed with 2FA enabled. To fix, see https://sendgrid.com/docs/for-developers/sending-email/authentication/#basic-authentication
00:03:09.400  
00:03:09.400  	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:965)
00:03:09.400  	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:876)
00:03:09.400  	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:780)
00:03:09.400  	at javax.mail.Service.connect(Service.java:388)
00:03:09.400  	at javax.mail.Service.connect(Service.java:246)
00:03:09.400  	at javax.mail.Service.connect(Service.java:195)
00:03:09.400  	at javax.mail.Transport.send0(Transport.java:254)
00:03:09.400  	at javax.mail.Transport.send(Transport.java:124)
00:03:09.400  	at org.jenkinsci.plugins.workflow.steps.MailStep$MailStepExecution.run(MailStep.java:143)
00:03:09.400  	at org.jenkinsci.plugins.workflow.steps.MailStep$MailStepExecution.run(MailStep.java:129)
00:03:09.400  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
00:03:09.400  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
00:03:09.400  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
00:03:09.400  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
00:03:09.400  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
00:03:09.401  	at java.base/java.lang.Thread.run(Thread.java:829)
00:03:09.410  Finished: FAILURE
```

**Comment by dduportal** [comment]
After discussions in IRC:

- Neither @olblak @timja or I have access to sendgrid. Sounds like it's KK only (maybe @MarkEWaite ?).
- ci.jenkins.io has the same configuration as trusted.ci.jenkins.io regarding SMTP settings: both are using smtp.sendgrid
- We want to remove this setting as both of these instances aren't able to send email (and we don't want them to).
- For the rest of usage for sendgrid, we want to switch to Azure service (out of the scope of this issue)

**Comment by dduportal** [comment]
- Configuration for SMTP removed from both trusted.ci.jenkins.io and ci.jenkins.io. No more error log.
- Thought about adding the "no smtp" settings to JCasc, but it appears that the default is "empty".
