### ISSUE TITLE
[ci.jenkins.io] Windows VM agents slow or unavailable

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2949]
### Service(s)

ci.jenkins.io

### Summary

Since a few days (haven't check the start date), ci.jenkins.io fails to spin up Windows VM agents on Azure:

- Only EC2 is used to spin up machines, which decreases the amount of run that can be run at the same time (potential incraesed queue)
- Cloud Statistics are clearly showing this behavior:
<img width="346" alt="Capture d’écran 2022-05-21 à 14 06 05" src="https://user-images.githubusercontent.com/1522731/169650799-abef949d-f33b-4271-b5a1-a8efd6981462.png">

**Comment by dduportal** [comment]
Diagnostic:
- In ci.jenkins.io, once logged-in (as admin), click on the "Cloud Statistics" section's title, on the left column. You are redirected to a page with the list of deployments for all Azure "kinds". On the column "provisionning", click on the error exceprt of one of the failed Windows Azure deployements to check the error message:

```console
com.microsoft.azure.vmagent.exceptions.AzureCloudException: Deployment Failed: Microsoft.Compute/virtualMachines:win-201-904ad0 - Conflict - com.azure.resourcemanager.resources.models.StatusMessage@15b5af97
	at com.microsoft.azure.vmagent.exceptions.AzureCloudException.create(AzureCloudException.java:37)
	at com.microsoft.azure.vmagent.AzureVMCloud.createProvisionedAgent(AzureVMCloud.java:548)
	at com.microsoft.azure.vmagent.AzureVMCloud$2.call(AzureVMCloud.java:771)
	at com.microsoft.azure.vmagent.AzureVMCloud$2.call(AzureVMCloud.java:748)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

=> No "Azure API client side" useful message, let's check on Azure portal (e.g. "API Server side").

- In the Azure portal, browsing to the "Resources Groups" section, choosing `eastus-cijenkinsio`, and then browsing to its "Deployments" section, we can see the failure to deploy the windows VMs. Retrieved an error message from one of these failed deployments:

```console
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"OperationNotAllowed","message":"The specified disk size 90 GB is smaller than the size of the corresponding disk in the VM image: 128 GB. This is not allowed. Please choose equal or greater size or do not specify an explicit size."}]}
```

**Comment by dduportal** [comment]
Root cause:

- https://github.com/jenkins-infra/packer-images/blob/main/locals.pkr.hcl#L22 specifies a 128 Gb disk size for Windows VM templates
- Introduced in https://github.com/jenkins-infra/packer-images/pull/221, e.g. since https://github.com/jenkins-infra/packer-images/releases/tag/0.24.4, applied to ci.jenkins.io since 7 days, by https://github.com/jenkins-infra/jenkins-infra/pull/2174.

**Comment by dduportal** [comment]
Incoming fix: setting up the VM size to 128Gb for Windows VM agents (PR https://github.com/jenkins-infra/jenkins-infra/pull/2180) with automatic tracking with updatecli to avoid reproducing such issue (or detect it earlier)

**Comment by dduportal** [comment]
- Azure Windows VM are now working again on ci.jenkins.io: https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/check-agent-availability/958/console
- Added Azure VMs as part of https://github.com/jenkins-infra/acceptance-tests/pull/31 (infra acceptance tests)
- Checked non regression on trusted.ci: https://trusted.ci.jenkins.io:1443/job/Containers/job/jnlp-agents/1175/
