### ISSUE TITLE
Update Center stopped updating: job failing on trusted.ci.jenkins.io with error `java.io.FileNotFoundException` `(File name too long)`

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3019]
### Service(s)

Update center

### Summary

Error is:

```console
09:45:08 Exception in thread "main" java.io.FileNotFoundException: caches/artifactory/<redacted> (File name too long)
09:45:08 	at java.io.FileOutputStream.open0(Native Method)
09:45:08 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
09:45:08 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
09:45:08 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
09:45:08 	at io.jenkins.update_center.ArtifactoryRepositoryImpl.getFile(ArtifactoryRepositoryImpl.java:248)
09:45:08 	at io.jenkins.update_center.ArtifactoryRepositoryImpl.getFileContent(ArtifactoryRepositoryImpl.java:225)
09:45:08 	at io.jenkins.update_center.ArtifactoryRepositoryImpl.getManifest(ArtifactoryRepositoryImpl.java:212)
09:45:08 	at io.jenkins.update_center.MavenArtifact.getManifest(MavenArtifact.java:124)
09:45:08 	at io.jenkins.update_center.MavenArtifact.getManifestAttributes(MavenArtifact.java:130)
09:45:08 	at io.jenkins.update_center.HPI.getPluginUrl(HPI.java:342)
09:45:08 	at io.jenkins.update_center.json.PluginDocumentationUrlsRoot.<init>(PluginDocumentationUrlsRoot.java:18)
09:45:08 	at io.jenkins.update_center.Main.run(Main.java:259)
09:45:08 	at io.jenkins.update_center.Main.run(Main.java:198)
09:45:08 	at io.jenkins.update_center.Main.main(Main.java:172)
```

right after this line (this is the too long plugion name):

```console
Caused by the plugin https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/aws-java-sdk/aws-java-sdk-elasticbeanstalk/1.12.246-349.v96b_b_f7eb_a_c3c/aws-java-sdk-elasticbeanstalk-1.12.246-349.v96b_b_f7eb_a_c3c.hpi!/META-INF/MANIFEST.MF (not found in cache)
```

**Comment by dduportal** [comment]
There was https://github.com/jenkins-infra/update-center2/pull/551 also (useful link)

**Comment by dduportal** [comment]
Ping @timja @daniel-beck I assume that we have to do a short-term fix like https://github.com/jenkins-infra/update-center2/pull/314 to add the faulty plugin to `artifact.properties` ?

Or is there a way to only ignore caching for such plugin name?

**Comment by timja** [comment]
You can append the version number like in https://github.com/jenkins-infra/update-center2/blob/13e3289acc1f65705411c19106392ffabc9df311/src/main/resources/artifact-ignores.properties#L240

but given it's a multi module plugin you probably want to block all modules in that release.

cc'ing @jglick and @vlatombe as well

**Comment by dduportal** [comment]
I'm not sure to understand the consequences of the fix: will it remove the plugin from the update center? Will it only ignore the cache ? It's not clear and I can't find a  correct documentation except what was written on the issues/PR that I'm linking.

I need help :)

**Comment by dduportal** [comment]
Caught by @MarkEWaite : The "faulty" version seems to have `_` in their name (https://github.com/jenkinsci/aws-java-sdk-plugin/releases/tag/1.12.246-349.v96b_b_f7eb_a_c3c) while previous did not (https://github.com/jenkinsci/aws-java-sdk-plugin/releases/tag/1.12.215-343.v953e693f0e86). This plugin is "close" to the edge of the max limit in characters.

**Comment by timja** [comment]
It will remove either the plugin or the plugin and version if you specify the version from the update center.

**Comment by jglick** [comment]
The `_` is intentional (works around a bug in Dependabot).

**Comment by MarkEWaite** [comment]
> The `_` is intentional (works around a bug in Dependabot).

Agreed and understood that the character is needed and not optional

**Comment by jglick** [comment]
Better to fix https://github.com/jenkins-infra/helpdesk/issues/1968 rather than waste time trying to chase workarounds.

**Comment by dduportal** [comment]
- https://github.com/jenkins-infra/update-center2/pull/606 merged => update center are green again.
- Currently working with @smerle33 to ensure that all recent plugins updates are caught and deployed (case of update_center not covering all the past hours

**Comment by dduportal** [comment]
- All released plugins that could have been missing have been deployed, following the runbook about "updates" (operation entirely done by @smerle33 so I'm not a bus factor :) ).

**Comment by MarkEWaite** [comment]
For reference, Jenkins Jira https://issues.jenkins.io/browse/JENKINS-68834 reports the issue for users updating to the most recent release of plugins that require the AWS Java SDK Elasticbeanstalk plugin

**Comment by dduportal** [comment]
> For reference, Jenkins Jira https://issues.jenkins.io/browse/JENKINS-68834 reports the issue for users updating to the most recent release of plugins that require the AWS Java SDK Elasticbeanstalk plugin

Damn :'( Should be add the whole `aws-*` list for this version to the exclusion list?

**Comment by MarkEWaite** [comment]
I don't think we should spend the extra effort to block multiple releases unless the investigation next week shows that we can't resolve the root problem.  The idea from @jglick to read the cache in the old format and write new entries in the new format seems very promising.

**Comment by dduportal** [comment]
Given the potential impact of switching cache from base64 to sha256, the worst case scenario is to duplicate the amount of data or loose the actual cache (which takes hours to repopulate).

Just ran the following operations to ensure infrrastucture safety:

- Created a snapshot of the datavolume of 300 Gb mounted to `/home/jenkins` on the agent, named `helpdesk-3019-20220625` (just in case we need to rollback, that would allow the actual version of the base64 code to run as expected with only the gap from today until we "break it" to fill).
- Extended the data volume from 300 to 600 Gb following https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/recognize-expanded-volume-linux.html instructions (extend volume on EC2, locate volume on Linux instance, grow the volume on linux instance, resise filesystem to use the whole volume):

```console
root@ip-172-31-5-190:/# df -hT /home/jenkins /
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/xvdf1     ext4  591G  174G  390G  31% /home/jenkins
/dev/xvda1     ext4   99G   15G   80G  16% /
```

**Comment by dduportal** [comment]
- Additionnaly, checking the state of the "persistent" workspace for this agent. It appears that the cache weight ~46 Gb while there is a huge (111G) `download/` folder (which maps to https://github.com/jenkins-infra/update-center2/blob/2614de4cd8b94570547b1930b8829e59f3646802/src/main/java/io/jenkins/update_center/DirectoryTreeBuilder.java#L34).

```console
update_center# du -sh *
46G	caches
8.0K	CHANGELOG.adoc
111G	download
4.0K	Jenkinsfile
2.9M	jq
12K	pom.xml
16K	README.adoc
464K	resources
100K	site
4.0K	spotbugs-excludes.xml
560K	src
27M	tmp
36K	www2
```

- Currently creating a rsync copy of the cache to `/home/jenkins`. The download directory will follow 'just in case'.

**Comment by daniel-beck** [comment]
Out of curiosity, why is there a need for a "hotfix" like https://github.com/jenkins-infra/update-center2/pull/606? Is it that bad if the UC doesn't update over a weekend?

**Comment by dduportal** [comment]
> Out of curiosity, why is there a need for a "hotfix" like [jenkins-infra/update-center2#606](https://github.com/jenkins-infra/update-center2/pull/606)? Is it that bad if the UC doesn't update over a weekend?

Good question.

with the «infra support hat » i say yes, because the amount of plugin developers that will waste their time trying to understand why their release is not available, and eventually opening issues, is not the best situation.

on the other way, what we did causes error for end users when installing the aws plugins, so not good either.

freezing update center updates for a week end, if associated with a good communication to developer might have been better

**Comment by MarkEWaite** [comment]
> on the other way, what we did causes error for end users when installing the aws plugins, so not good either.

Weren't users of the AWS plugins going to be affected either way?  If the update center data did not refresh over the weekend, wouldn't they have suffered the same problem as they are suffering now?

**Comment by dduportal** [comment]
> > on the other way, what we did causes error for end users when installing the aws plugins, so not good either.
> 
> Weren't users of the AWS plugins going to be affected either way? If the update center data did not refresh over the weekend, wouldn't they have suffered the same problem as they are suffering now?

I'm not sure: if the plugins were released "at the same time or in the correct order (dependencies first)", then the regular update_center update would have failed on the dependency without being able to publish the others.
Keeping the update center frozen would have kept a "stable" situation. 

Good learning experience here for us: it's a step in understanding (and managing) better the update_center system :)

For info, I plan to try Jesse's pull request later today, that would fix once for all these issues :)

**Comment by timja** [comment]
> but given it's a multi module plugin you probably want to block all modules in that release.

FTR 😄

**Comment by dduportal** [comment]
> 

Fair ;) But it was not easy how to connect the dots (at least for me or the infra team) without knowing all the details.
Heh, we failed, but we learned at least :)

**Comment by dduportal** [comment]
Test of https://github.com/jenkins-infra/update-center2/pull/605 in progress (see details in the PR)

**Comment by dduportal** [comment]
- Test of Jesse's PR is successful. To be confirmed by someone else, but ready to be merged and deployed
- Cache is snapshoted and copied: we can go forward as soon as posible!

**Comment by tpak** [comment]
Hi, just wanted to drop in and say thanks for all the hard work over the last few days. FWIW, I was pulling my hair out Saturday AM (US time) trying to understand why updating wasn't working. We'd just finally moved to Java 11 and thought maybe it was an issue with that and the AWS plugins somehow - oops. (don't ask why on the Java update until after support ended, I don't know either!) 
In any case, finally found the Jira issue https://issues.jenkins.io/browse/JENKINS-68834 and followed the breadcrumbs here after we rolled back to just prior to the Java update.
Only dropping that backstory since you were having a discussion re: impact to devs and users and it wasn't just devs going in circles trying to figure it out 🫤
In any case, thanks again for getting this sorted!

**Comment by daniel-beck** [comment]
We also needed https://github.com/jenkins-infra/update-center2/pull/613 but now this should finally be resolved.

**Comment by HaeyoonJo** [comment]
Thank you so much for your work!

**Comment by dduportal** [comment]
Thanks everyone for the work invovlved, but also for feedbacks and reportings.

We'll try to avoid breaking plugin tree if such situation occurs again.

The update_center build is now working successfully with the new cache, so closing the issue.

Please feel free to reopen if you see any errors stil present.
