### ISSUE TITLE
502 proxy error when accessing PR view for jenkinsci/jenkins

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3029]
### Service(s)

ci.jenkins.io

### Summary

If I try to access the PR view of jenkinsci/jenkins on https://ci.jenkins.io/job/Core/job/jenkins/view/change-requests/, I get a 502 proxy error:
![Bildschirmfoto 2022-06-29 um 21 13 02](https://user-images.githubusercontent.com/13383509/176517432-502216e8-b53d-4f62-9b8a-14b01dcd3a57.png)
Does anyone else experience that too? Other views, folders and jobs are unaffected.

**Comment by MarkEWaite** [comment]
Thanks for reporting the issue.  I see the same message as well.  No idea why Jenkins core has that problem on that page when other projects in the same folder (like acceptance test harness) do not have the problem.

**Comment by daniel-beck** [comment]
502 happens when Jenkins takes too long processing the request.

I just accessed the URL linked, and opened a thread dump at the same time, and there were two separate requests from two different IP addressed, both stack traces pointing at coverage column:

``` 
"Handling GET /job/Core/job/jenkins/view/change-requests/ from redacted : Jetty (winstone)-272292 View/index.jelly CoverageColumn/column.jelly" Id=272292 Group=main RUNNABLE
	at java.base@11.0.15/java.util.Arrays.copyOfRange(Arrays.java:4030)
	at java.base@11.0.15/java.lang.StringLatin1.newString(StringLatin1.java:715)
	at java.base@11.0.15/java.lang.StringBuffer.toString(StringBuffer.java:720)
	at com.thoughtworks.xstream.io.path.PathTracker.peekElement(PathTracker.java:133)
	at com.thoughtworks.xstream.io.path.PathTracker.getPath(PathTracker.java:169)
	at com.thoughtworks.xstream.core.ReferenceByXPathUnmarshaller.getCurrentReferenceKey(ReferenceByXPathUnmarshaller.java:41)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readBareItem(AbstractCollectionConverter.java:132)
	at hudson.util.RobustCollectionConverter.populateCollection(RobustCollectionConverter.java:87)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:81)
	at hudson.util.RobustCollectionConverter.unmarshal(RobustCollectionConverter.java:78)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
	at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:454)
	at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:350)
	at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:289)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readBareItem(AbstractCollectionConverter.java:132)
	at hudson.util.RobustCollectionConverter.populateCollection(RobustCollectionConverter.java:87)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:81)
	at hudson.util.RobustCollectionConverter.unmarshal(RobustCollectionConverter.java:78)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
	at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:454)
	at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:350)
	at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:289)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readBareItem(AbstractCollectionConverter.java:132)
	at hudson.util.RobustCollectionConverter.populateCollection(RobustCollectionConverter.java:87)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:81)
	at hudson.util.RobustCollectionConverter.unmarshal(RobustCollectionConverter.java:78)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
	at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:454)
	at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:350)
	at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:289)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readBareItem(AbstractCollectionConverter.java:132)
	at hudson.util.RobustCollectionConverter.populateCollection(RobustCollectionConverter.java:87)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:81)
	at hudson.util.RobustCollectionConverter.unmarshal(RobustCollectionConverter.java:78)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
	at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:454)
	at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:350)
	at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:289)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readBareItem(AbstractCollectionConverter.java:132)
	at hudson.util.RobustCollectionConverter.populateCollection(RobustCollectionConverter.java:87)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:81)
	at hudson.util.RobustCollectionConverter.unmarshal(RobustCollectionConverter.java:78)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
	at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:454)
	at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:350)
	at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:289)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:136)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1421)
	at hudson.util.XStream2.unmarshal(XStream2.java:189)
	at hudson.util.XStream2.unmarshal(XStream2.java:160)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1399)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1293)
	at hudson.XmlFile.read(XmlFile.java:165)
	at io.jenkins.plugins.util.AbstractXmlStream.readXml(AbstractXmlStream.java:105)
	at io.jenkins.plugins.util.AbstractXmlStream.read(AbstractXmlStream.java:79)
	at io.jenkins.plugins.util.BuildAction.readResult(BuildAction.java:138)
	at io.jenkins.plugins.util.BuildAction.getResult(BuildAction.java:128)
	at io.jenkins.plugins.coverage.model.CoverageBuildAction.hasCoverage(CoverageBuildAction.java:165)
	at io.jenkins.plugins.coverage.model.visualization.dashboard.ProjectCoverage.getCoverage(ProjectCoverage.java:29)
	at io.jenkins.plugins.coverage.model.visualization.dashboard.CoverageColumn.getCoverageValue(CoverageColumn.java:136)
	at io.jenkins.plugins.coverage.model.visualization.dashboard.CoverageColumn.getCoverageText(CoverageColumn.java:118)
	…
	at hudson.model.View.main.run(main.groovy:16)
    …

"Handling GET /job/Core/job/jenkins/view/change-requests/ from redacted : Jetty (winstone)-270501 View/index.jelly CoverageColumn/column.jelly" Id=270501 Group=main RUNNABLE
	at java.base@11.0.15/java.util.ArrayList.spliterator(ArrayList.java:1561)
	at java.base@11.0.15/java.util.Collection.stream(Collection.java:711)
	at io.jenkins.plugins.coverage.model.CoverageNode.getCoverage(CoverageNode.java:338)
	at io.jenkins.plugins.coverage.model.CoverageNode.lambda$getCoverage$4(CoverageNode.java:336)
	at io.jenkins.plugins.coverage.model.CoverageNode$$Lambda$2032/0x0000000801f41040.apply(Unknown Source)
	at java.base@11.0.15/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base@11.0.15/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base@11.0.15/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@11.0.15/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:553)
	at io.jenkins.plugins.coverage.model.CoverageNode.getCoverage(CoverageNode.java:337)
	at io.jenkins.plugins.coverage.model.CoverageNode.lambda$getCoverage$4(CoverageNode.java:336)
	at io.jenkins.plugins.coverage.model.CoverageNode$$Lambda$2032/0x0000000801f41040.apply(Unknown Source)
	at java.base@11.0.15/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base@11.0.15/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base@11.0.15/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@11.0.15/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:553)
	at io.jenkins.plugins.coverage.model.CoverageNode.getCoverage(CoverageNode.java:337)
	at io.jenkins.plugins.coverage.model.CoverageNode.lambda$getCoverage$4(CoverageNode.java:336)
	at io.jenkins.plugins.coverage.model.CoverageNode$$Lambda$2032/0x0000000801f41040.apply(Unknown Source)
	at java.base@11.0.15/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base@11.0.15/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base@11.0.15/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@11.0.15/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:553)
	at io.jenkins.plugins.coverage.model.CoverageNode.getCoverage(CoverageNode.java:337)
	at io.jenkins.plugins.coverage.model.CoverageNode.lambda$getCoverage$4(CoverageNode.java:336)
	at io.jenkins.plugins.coverage.model.CoverageNode$$Lambda$2032/0x0000000801f41040.apply(Unknown Source)
	at java.base@11.0.15/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base@11.0.15/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base@11.0.15/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@11.0.15/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:553)
	at io.jenkins.plugins.coverage.model.CoverageNode.getCoverage(CoverageNode.java:337)
	at io.jenkins.plugins.coverage.model.CoverageNode.lambda$getCoverage$4(CoverageNode.java:336)
	at io.jenkins.plugins.coverage.model.CoverageNode$$Lambda$2032/0x0000000801f41040.apply(Unknown Source)
	at java.base@11.0.15/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base@11.0.15/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base@11.0.15/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@11.0.15/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:553)
	at io.jenkins.plugins.coverage.model.CoverageNode.getCoverage(CoverageNode.java:337)
	at io.jenkins.plugins.coverage.model.CoverageBuildAction.hasCoverage(CoverageBuildAction.java:165)
	at io.jenkins.plugins.coverage.model.visualization.dashboard.ProjectCoverage.getCoverage(ProjectCoverage.java:29)
	at io.jenkins.plugins.coverage.model.visualization.dashboard.CoverageColumn.getCoverageValue(CoverageColumn.java:136)
	…
	at lib.JenkinsTagLib$projectView$1.call(Unknown Source)
	at hudson.model.View.main.run(main.groovy:16)

**Comment by dduportal** [comment]
I'm not sure what should we do (I don't even know what is "Code Coverage Column"). Could one of you give us a pointer to the next steps so the infra team can do something about it?

**Comment by NotMyFault** [comment]
Afaik, that's added by https://github.com/jenkinsci/code-coverage-api-plugin and is part of the default [pipeline library](https://github.com/jenkins-infra/pipeline-library/blob/b9d6e3b31dd4191b7cbfffba02b9ae57e735836c/vars/buildPlugin.groovy#L131) used for Jenkinsfiles as well.

I'm not too sure if this is an infra or plugin issue, maybe the chart is just overloaded rendering the results?
As temp fix we could remove it from core, if that is actually the culprit.

**Comment by uhafner** [comment]
It would be helpful if someone would report such problems in the plugin, otherwise it's hard to know that we have a problem here 🤷

**Comment by uhafner** [comment]
Fixed in https://github.com/jenkinsci/code-coverage-api-plugin/releases/tag/v3.0.3

**Comment by medianick** [comment]
This might be what we experienced after the 3.0.0 upgrade to the Code Coverage API plugin (which we hadn't definitively traced to that plugin, so hadn't yet reported it as a bug, but suspected it): namely, a significant performance regression when viewing multibranch pipeline jobs (listing branches or PRs). For us, a display of ~100 PRs now takes over 60 seconds.

**Comment by dduportal** [comment]
Wow that was a tricky bug (at least from a Jenkins admin point of view).

Many thanks @daniel-beck for the threaddump and analysis, many thanks @uhafner  for the quick fix and many thanks @NotMyFault for the help and raising the issue!

Latest Coverage plugin (and dependencies) had been applied to ci.jenkins.io: the page https://ci.jenkins.io/job/Core/job/jenkins/view/change-requests/ shows in less than 2s on my machine, so closing this issue.
