### ISSUE TITLE
Docker-compose in JenkinsCI.io

### ISSUE THREAD

**Issue by rvansa** [jenkins-infra/helpdesk#3039]
### Service(s)

ci.jenkins.io

### Summary

Hello,

my plugin that I am trying to release ( https://github.com/jenkinsci/horreum-plugin/pull/2 ) uses Testcontainers with local `docker-compose` to setup the the containers the tests should run against. Regrettably the tests are failing because of missing `docker-compose` on `linux` platform; I have disabled `windows` because of missing `docker` as well.

```
org.testcontainers.containers.ContainerLaunchException: Local Docker Compose exited abnormally with code 18 whilst running command: up -d
	at org.testcontainers.containers.LocalDockerCompose.invoke(DockerComposeContainer.java:775)
	at org.testcontainers.containers.DockerComposeContainer.runWithCompose(DockerComposeContainer.java:311)
	at org.testcontainers.containers.DockerComposeContainer.createServices(DockerComposeContainer.java:235)
	at org.testcontainers.containers.DockerComposeContainer.start(DockerComposeContainer.java:177)
	at io.hyperfoil.tools.HorreumTestExtension.startContainers(HorreumTestExtension.java:196)
```

Is there a way to use `docker-compose` or otherwise customize the image the build uses?

Thanks

**Comment by dduportal** [comment]
@rvansa no problem. Now you now where to open issues and get help :)

I confirm that, by default, the `buildPlugin()` pipeline library uses a fully fledged VM with a Docker Engine (wether it's Windows or Linux).

You build ran on a VM with a Docker Engine. However it appears that it was an `ARM64` VM, which explains the failure. Sorry for that: we are working on this.

**Comment by dduportal** [comment]
Hi @rvansa the problem should be definitively fixed! Thanks for reporting and contributing to Jenkins!
