### ISSUE TITLE
checks-api 1.7.5: download plugin checks-api to file: status code: 403, reason phrase: Forbidden

### ISSUE THREAD

**Issue by brovoca** [jenkins-infra/helpdesk#3095]
### Service(s)

Archives, plugins.jenkins.io

### Summary

Unable to resolve plugin URL https://archives.jenkins.io/plugins/checks-api/1.7.5/checks-api.hpi, or download plugin checks-api to file: status code: 403, reason phrase: Forbidden

### Reproduction steps

```sh
# jenkins-plugin-cli --verbose --war "$JENKINS_WAR" --plugin-download-directory "$JENKINS_HOME/plugins" --plugins "checks-api" --latest "false"
...
Unable to resolve plugin URL https://archives.jenkins.io/plugins/checks-api/1.7.5/checks-api.hpi, or download plugin checks-api to file: status code: 403, reason phrase: Forbidden
io.jenkins.tools.pluginmanager.impl.DownloadPluginException: Unable to download checks-api
    at io.jenkins.tools.pluginmanager.impl.PluginManager.lambda$downloadPlugins$4(PluginManager.java:565)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
    at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
    at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Unable to download checks-api
```

Sometimes it works though, when it resolves a different host:
```log
Downloaded checks-api from https://ftp-nyc.osuosl.org/pub/jenkins/plugins/checks-api/1.7.5/checks-api.hpi (attempt 1 of 3)
```

**Comment by dduportal** [comment]
Hi @brovoca , thanks for reporting. We have had an issue on the update center for the past hours, but it should be fixed (matter of time for propagation on all download servers)

On my side, I can now successfully download from the URL you shared (on archives.jenkins.io) which means it was fixed in the time interval between when you opened the issue and my comment now.

Can you confirm it's working now for you please?

**Comment by brovoca** [comment]
Yep, works now :-)

**Comment by dduportal** [comment]
Thanks for the answer! Gotta close the issue. Feel free to reopen if you see any other issue.

**Comment by daniel-beck** [comment]
> We have had an issue on the update center for the past hours, but it should be fixed (matter of time for propagation on all download servers)

FTR from yesterday around 11:30 PM CEST to this morning 9 AM, the update center did not update. This didn't cause problems other than make a few plugin updates released during this time not available.

This morning from around 9 AM to around 9:50 AM, some plugin updates were advertised but could not be downloaded, most prominently by far `checks-api`.
