### ISSUE TITLE
ci.jenkins.io failing with windows build & parcel node packager

### ISSUE THREAD

**Issue by jgreffe** [jenkins-infra/helpdesk#3105]
### Service(s)

ci.jenkins.io

### Summary

When building this plugin: https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fpipeline-stage-view-plugin/detail/PR-240/2/pipeline/92/

windows build fails when processing node with `parcel` packager:
```
[2022-08-19T13:53:12.412Z] [INFO] --- frontend-maven-plugin:1.12.1:npm (npm mvnbuild) @ pipeline-stage-view ---
[2022-08-19T13:53:12.412Z] [INFO] testFailureIgnore property is ignored in non test phases
[2022-08-19T13:53:12.412Z] [INFO] Running 'npm run mvnbuild' in C:\Jenkins\workspace\ipeline-stage-view-plugin_PR-240\ui
[2022-08-19T13:53:12.412Z] [INFO] 
[2022-08-19T13:53:12.412Z] [INFO] > pipeline-stage-view@0.0.1 mvnbuild
[2022-08-19T13:53:12.412Z] [INFO] > parcel build --public-url ./ ./src/main/js/stageview.js --dist-dir ./src/main/webapp/jsmodules && parcel build --public-url ./ ./src/main/js/stageview_adjunct.js --dist-dir ./target/generated-adjuncts/org/jenkinsci/pipeline
[2022-08-19T13:53:12.412Z] [INFO] 
[2022-08-19T13:53:12.412Z] [INFO] Error: The specified module could not be found.
[2022-08-19T13:53:12.412Z] [INFO] \\?\C:\Jenkins\workspace\ipeline-stage-view-plugin_PR-240\ui\node_modules\@parcel\source-map\parcel_sourcemap_node\artifacts\index.win32-x64-msvc.node
[2022-08-19T13:53:12.412Z] [INFO]     at Module._extensions..node (node:internal/modules/cjs/loader:1204:18)
[2022-08-19T13:53:12.412Z] [INFO]     at Module.load (node:internal/modules/cjs/loader:998:32)
[2022-08-19T13:53:12.412Z] [INFO]     at Module._load (node:internal/modules/cjs/loader:839:12)
[2022-08-19T13:53:12.412Z] [INFO]     at Module.require (node:internal/modules/cjs/loader:1022:19)
[2022-08-19T13:53:12.412Z] [INFO]     at require (C:\Jenkins\workspace\ipeline-stage-view-plugin_PR-240\ui\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
[2022-08-19T13:53:12.412Z] [INFO]     at Object.<anonymous> (C:\Jenkins\workspace\ipeline-stage-view-plugin_PR-240\ui\node_modules\@parcel\source-map\parcel_sourcemap_node\index.js:15:18)
[2022-08-19T13:53:12.412Z] [INFO]     at Module._compile (C:\Jenkins\workspace\ipeline-stage-view-plugin_PR-240\ui\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
[2022-08-19T13:53:12.412Z] [INFO]     at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
[2022-08-19T13:53:12.412Z] [INFO]     at Module.load (node:internal/modules/cjs/loader:998:32)
[2022-08-19T13:53:12.412Z] [INFO]     at Module._load (node:internal/modules/cjs/loader:839:12) {
[2022-08-19T13:53:12.412Z] [INFO]   code: 'ERR_DLOPEN_FAILED'
[2022-08-19T13:53:12.412Z] [INFO] }
```

Same repository built on a bare windows 10 machine succeeds.

Could be related to windows image used:
```
[2022-08-19T13:44:58.210Z] Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
[2022-08-19T13:44:58.210Z] Maven home: C:\ProgramData\Maven
[2022-08-19T13:44:58.210Z] Java version: 1.8.0_312, vendor: Temurin, runtime: C:\openjdk-8\jre
[2022-08-19T13:44:58.210Z] Default locale: en_US, platform encoding: Cp1252
[2022-08-19T13:44:58.489Z] OS name: "windows server 2019", version: "10.0", arch: "amd64", family: "windows"
```

Suggested fix is to set `useContainerAgent` to `false` in `Jenkinsfile`:
```
buildPlugin(useContainerAgent: false, configurations: [
  [ platform: "linux", jdk: "8" ],
  [ platform: "windows", jdk: "8" ],
  [ platform: "linux", jdk: "11" ]
])
```

**Comment by lemeurherve** [comment]
Comparing this PR with the next one which is passing, the main difference seems to be the use of `parcel` in the plugin now.
I'm wondering if `parcel` should be added to the agent tools

**Comment by jgreffe** [comment]
Not sure `parcel` should be added, because it's installed through `npm install --silent`.
I feel issue is related to `index.win32-x64-msvc.node`, maybe some missing DLL or other optional library not installed (?)
I found some similar issues, and seems linked to MS Visual C++: https://github.com/parcel-bundler/parcel/issues/7104#issuecomment-967260755

Also, using `buildPlugin(useContainerAgent: false, configurations: [` leads to same issue :/

**Comment by lemeurherve** [comment]
> Also, using buildPlugin(useContainerAgent: false, configurations: [ leads to same issue, and windows seems the same:

This is normal. Since you don't have the required rights, you can't use modification made to Jenkinsfile for a pull request build as it would allow bad things™

> 10:35:05  Connecting to https://api.github.com/ to check permissions of obtain list of jgreffe for jenkinsci/pipeline-stage-view-plugin
> 10:35:05  Loading trusted files from base branch master at 341bbdb77b1c39c076c8c15e82be490e0839de37 rather than 328c815cc40c3d2e61da31eba127028520c1da09
> 10:35:05  Obtained Jenkinsfile from 341bbdb77b1c39c076c8c15e82be490e0839de37
> 10:35:05  ‘Jenkinsfile’ has been modified in an untrusted revision

I've replayed your build with `useContainer: false`, it finished with success, you're good to go for your PR 🙂 

Unfortunately (for me), as I missed that permission issue before adding Microsoft Visual C++ 2015 Redistributable to the Windows packer image, I'm not sure its addition was required.

@dduportal WDYT? Should I try to revert the template to check if only `useContainer: false` is enough, or should I let it as it is?

**Comment by jgreffe** [comment]
@lemeurherve : yeepee!! 🎉 

This means we'll have to ask you to trigger builds whenever we change this `useContainer: false` in any repository?

BTW, we have the exact same issue for this PR:
https://github.com/cloudbees/cloudbees-workflow-ui-plugin/pull/22
https://gauntlet-3.cloudbees.com/gaia/blue/organizations/jenkins/Atlas%2FPlugins%2Fcloudbees-workflow-ui-plugin/detail/PR-22/5/pipeline
But I can't find any `Jenkinsfile`. Should we update `.gaia` file in order to use a specific windows container?

cc @scherler

**Comment by lemeurherve** [comment]
> This means we'll have to ask you to trigger builds whenever we change this useContainer: false in any repository?

This means to be able to run PR builds on Jenkinsfile changes, the pull request has to be opened by one of the maintainer of the repository/plugin.

> BTW, we have the exact same issue for this PR:
> https://github.com/cloudbees/cloudbees-workflow-ui-plugin/pull/22
> [gauntlet-3.cloudbees.com/gaia/blue/organizations/jenkins/Atlas%2FPlugins%2Fcloudbees-workflow-ui-plugin/detail/PR-22/5/pipeline](https://gauntlet-3.cloudbees.com/gaia/blue/organizations/jenkins/Atlas%2FPlugins%2Fcloudbees-workflow-ui-plugin/detail/PR-22/5/pipeline)
> But I can't find any Jenkinsfile. Should we update .gaia file in order to use a specific windows container?

Sorry I can't really help you as I don't know how Gauntlet is configured/working.

**Comment by jgreffe** [comment]
Thanks for your help, I'll ask in proper channel.
👍🏼

**Comment by lemeurherve** [comment]
Also note I'm still not sure if it works now because of the `useContainer: false`, or because of the addition of MS C++

**Comment by dduportal** [comment]
@jgreffe Regarding the OSS infra, the `useContainer: false` is a tempororary trick to force using VM agents.
But the infra-team is working on #2822 to provide the same template for VM and containers: once deployed you'll be able to rollback this hack :)

**Comment by dduportal** [comment]
> Also note I'm still not sure if it works now because of the `useContainer: false`, or because of the addition of MS C++

Both:
- useContainer ensure that a VM is used
- hence the VMs are now using the new template (I guess) with MS C++

**Comment by lemeurherve** [comment]
> Both

Good, closing this issue then.
