### ISSUE TITLE
Build failing for packer-images

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3124]
### Service(s)

Other

### Summary

The builds for the https://github.com/jenkins-infra/packer-images project are failing, which blocks us from releasing the 0.41.0 version.

No emergency to release (only minor updates of `az`, `gh` or packer providers) but we have to track the fix.

Some analysis after trying superfically to diagnose and reproduce:

- It's a Linux-only problem: All Windows images are built with success
- It's a VM-only problem: all Docker Linux builds are built with success
- It's *NOT* CPU-related: both arm and Intel builds on AWS are failing.

=> Only AWS EC2 Intel Ubuntu 20.04, AWS EC2 ARM64 Ubuntu 20.04 and Azure VM Intel Ubuntu 20.04 are failing.

The error appears during the "sanity check", when the `az` command line is called.
It throws the following python error:

```console
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:07Z: ==> amazon-ebs.ubuntu: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:07Z: ==> amazon-ebs.ubuntu: WARNING: Auto upgrade failed. name 'exit_code' is not defined
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu: Traceback (most recent call last):
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/knack/cli.py", line 225, in invoke
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     self.show_version()
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/__init__.py", line 121, in show_version
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     ver_string, updates_available_components = get_az_version_string()
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/util.py", line 367, in get_az_version_string
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     versions, success = get_cached_latest_versions(versions) if use_cache else _update_latest_from_github(versions)
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/util.py", line 311, in _update_latest_from_github
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     if not check_connectivity(max_retries=0):
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/util.py", line 837, in check_connectivity
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     import requests
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from urllib3.contrib import pyopenssl
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     import OpenSSL.SSL
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from OpenSSL import crypto, SSL
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     class X509StoreFlags(object):
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
[2022-09-09T10:25:14.366Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu: AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu: During handling of the above exception, another exception occurred:
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu: Traceback (most recent call last):
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     return _run_code(code, main_globals, None,
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     exec(code, run_globals)
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/azure/cli/__main__.py", line 49, in <module>
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     exit_code = cli_main(az_cli, sys.argv[1:])
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/azure/cli/__main__.py", line 36, in cli_main
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     return cli.invoke(args)
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/knack/cli.py", line 245, in invoke
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     exit_code = self.exception_handler(ex)
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/__init__.py", line 127, in exception_handler
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     return handle_exception(ex)
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/util.py", line 58, in handle_exception
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from msrestazure.azure_exceptions import CloudError
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/msrestazure/__init__.py", line 28, in <module>
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from .azure_configuration import AzureConfiguration
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/msrestazure/azure_configuration.py", line 34, in <module>
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from msrest import Configuration
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/msrest/__init__.py", line 28, in <module>
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from .configuration import Configuration
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/msrest/configuration.py", line 37, in <module>
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from .pipeline import Pipeline
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/msrest/pipeline/__init__.py", line 52, in <module>
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from requests.structures import CaseInsensitiveDict
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from urllib3.contrib import pyopenssl
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
[2022-09-09T10:25:14.367Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     import OpenSSL.SSL
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from OpenSSL import crypto, SSL
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     class X509StoreFlags(object):
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu: AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu: Error in sys.excepthook:
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu: Traceback (most recent call last):
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from apport.fileutils import likely_packaged, get_recent_crashes
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from apport.report import Report
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     import apport.fileutils
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     import requests
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from urllib3.contrib import pyopenssl
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     import OpenSSL.SSL
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from OpenSSL import crypto, SSL
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     class X509StoreFlags(object):
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu: AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu: Original exception was:
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu: Traceback (most recent call last):
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/knack/cli.py", line 225, in invoke
[2022-09-09T10:25:14.368Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     self.show_version()
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/__init__.py", line 121, in show_version
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     ver_string, updates_available_components = get_az_version_string()
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/util.py", line 367, in get_az_version_string
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     versions, success = get_cached_latest_versions(versions) if use_cache else _update_latest_from_github(versions)
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/util.py", line 311, in _update_latest_from_github
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     if not check_connectivity(max_retries=0):
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/util.py", line 837, in check_connectivity
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     import requests
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from urllib3.contrib import pyopenssl
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     import OpenSSL.SSL
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from OpenSSL import crypto, SSL
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     class X509StoreFlags(object):
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu: AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu: During handling of the above exception, another exception occurred:
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu: Traceback (most recent call last):
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     return _run_code(code, main_globals, None,
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     exec(code, run_globals)
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/azure/cli/__main__.py", line 49, in <module>
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     exit_code = cli_main(az_cli, sys.argv[1:])
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/azure/cli/__main__.py", line 36, in cli_main
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     return cli.invoke(args)
[2022-09-09T10:25:14.369Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/knack/cli.py", line 245, in invoke
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     exit_code = self.exception_handler(ex)
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/__init__.py", line 127, in exception_handler
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     return handle_exception(ex)
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/util.py", line 58, in handle_exception
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from msrestazure.azure_exceptions import CloudError
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/msrestazure/__init__.py", line 28, in <module>
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from .azure_configuration import AzureConfiguration
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/msrestazure/azure_configuration.py", line 34, in <module>
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from msrest import Configuration
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/msrest/__init__.py", line 28, in <module>
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from .configuration import Configuration
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/msrest/configuration.py", line 37, in <module>
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from .pipeline import Pipeline
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/local/lib/python3.8/dist-packages/msrest/pipeline/__init__.py", line 52, in <module>
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from requests.structures import CaseInsensitiveDict
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from urllib3.contrib import pyopenssl
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     import OpenSSL.SSL
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     from OpenSSL import crypto, SSL
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     class X509StoreFlags(object):
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu:     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
[2022-09-09T10:25:14.370Z] 2022-09-09T10:25:08Z: ==> amazon-ebs.ubuntu: AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

**Comment by dduportal** [comment]
- Last successful build is https://infra.ci.jenkins.io/job/infra-tools/job/packer-images/job/main/156/ the 6th of September at 09h51am UTC, commit [01a6db4](https://github.com/jenkins-infra/packer-images/commit/01a6db4bffebb9a4941e8ef89c2596f3d02f30c1)
- Error appearaed on the next build, https://infra.ci.jenkins.io/job/infra-tools/job/packer-images/job/main/157/, the 7th of September 09h58am UTC, with the SAME commit

=> It is not a code change, at first sight, in the packer provisioning.

**Comment by dduportal** [comment]
Base images did not change for AWS EC2 Intel Ubuntu 20.04: both builds were using `ami-0d68d031be2577777`. Did not check the 2 other failing branches but sounds like it's unrelated to base image

**Comment by dduportal** [comment]
Next steps: reproduce the issue from a local VM (or a local packer build to EC2 or Azure VM, as docker is not concerned). Smells like a dependency in the openssl chain, that would not be on the Docker image.

**Comment by dduportal** [comment]
By running the following command on a VM where the error is reproduced, the command works again:

```
pip3 install pyOpenSSL --upgrade
pip3 install cryptography --upgrade
```

Gotta try with the distribution's packages

**Comment by dduportal** [comment]
Fixed by https://github.com/jenkins-infra/packer-images/pull/335
