### ISSUE TITLE
(bug): mvn error on jvm 17 for the jenkins-infra-test-plugin

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3129]
### Service(s)

ci.jenkins.io

### Summary

While trying the 3 versions of jvm agent from the same all in one image (built with packer-images), the built fail on a mvn error : 
https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fjenkins-infra-test-plugin/detail/PR-49/3/pipeline/91

```
[2022-09-14T06:59:39.123Z] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.444 s <<< FAILURE! - in InjectedTest

[2022-09-14T06:59:39.123Z] [ERROR] InjectedTest.initializationError  Time elapsed: 0.005 s  <<< ERROR!

[2022-09-14T06:59:39.123Z] java.lang.ExceptionInInitializerError

[2022-09-14T06:59:39.123Z] 	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:824)

[2022-09-14T06:59:39.123Z] 	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)

[2022-09-14T06:59:39.123Z] 	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)

[2022-09-14T06:59:39.123Z] 	at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)

[2022-09-14T06:59:39.124Z] 	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)

[2022-09-14T06:59:39.124Z] 	at com.thoughtworks.xstream.XStream.<init>(XStream.java:378)

```

**Comment by basil** [comment]
This is not a problem with `ci.jenkins.io` but rather with trying to test `jenkins-infra-test-plugin` (whose `jenkins.version` is currently 2.249.3, which does not support Java 17) with Java 17. To test `jenkins-infra-test-plugin` with Java 17, either update `jenkins.version` in its `pom.xml` to a version of Jenkins that is compatible with Java 17 (Jenkins 2.355 or later on the weekly line, and Jenkins 2.346.1 or later on the LTS line), or adjust your `Jenkinsfile` to override the Jenkins version to a higher version in the Java 17 branch.

**Comment by smerle33** [comment]
> This is not a problem with `ci.jenkins.io` but rather with trying to test `jenkins-infra-test-plugin` (whose `jenkins.version` is currently 2.249.3, which does not support Java 17) with Java 17. To test `jenkins-infra-test-plugin` with Java 17, either update `jenkins.version` in its `pom.xml` to a version of Jenkins that is compatible with Java 17 (Jenkins 2.355 or later on the weekly line, and Jenkins 2.346.1 or later on the LTS line), or adjust your `Jenkinsfile` to override the Jenkins version to a higher version in the Java 17 branch.

sorry basil can you move your perfect answer here ? : https://github.com/jenkinsci/jenkins-infra-test-plugin/issues/51
I move this issue to it's correct place .. my mistake

**Comment by basil** [comment]
https://github.com/jenkinsci/jenkins-infra-test-plugin/issues/51#issuecomment-1246861225
