### ISSUE TITLE
Account recovery for @andytinkham

### ISSUE THREAD

**Issue by andytinkham** [jenkins-infra/helpdesk#3195]
### Service(s)

Accounts

### Summary

Forgot Password link for accounts.jenkins.io gives 500 error.  

I'm trying to recover my account password. I'm pretty sure I set up an account with the user name @andytinkham. I can't generate a Forgot Password mail though because I get a server error. I know the andytinkham account exists because I tried to create a new account and was told it already existed.

### Reproduction steps

1. Go to https://accounts.jenkins.io
2. Click "Forgot Password" link
3. Enter username "andytinkham"
4. Hit Reset button
5. Page displays Server error

**Comment by timja** [comment]
The logs are full of:

```
2022-10-21 07:29:41.360:WARN:oejs.HttpChannel:qtp1172535934-19: /doPasswordReset
javax.servlet.ServletException: javax.servlet.ServletException: com.sun.mail.smtp.SMTPSendFailedException: 550 Unauthenticated senders not allowed|
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:168)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
Caused by:
javax.servlet.ServletException: com.sun.mail.smtp.SMTPSendFailedException: 550 Unauthenticated senders not allowed|
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:816)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:694)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:240)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
```

Looking

**Comment by timja** [comment]
I've triggered a password reset for you check your email.

**Comment by dduportal** [comment]
@andytinkham wev'e deployed the required fixes in production: I've just tested a password reset on a test account I have and it worked perfectly.

Can you confirm if it is working for you now?

**Comment by timja** [comment]
Also tested on my test account for extra double checking 😄

**Comment by andytinkham** [comment]
> I've triggered a password reset for you check your email.

@timja - I did get the email you triggered but it pointed me at localhost:8080 for the URL provided in the mail.

> Can you confirm if it is working for you now?

@dduportal - The Forgot Password link did work for me this time. No server error and a new email does show up in my Inbox. The email does link to accounts.jenkins.io. Clicking it just takes me back to the login page again though - not any sort of page to change my password. It's getting munged by Outlook's urldefense stuff - could that be breaking the link?

**Comment by timja** [comment]
The password in the email should work for you to login and change it.

It should say something like: "Your temporary password is ..."

(even though my url pointed to localhost it should have worked just fine(

**Comment by andytinkham** [comment]
Yep, the temporary password worked. I've reset my password now (and put it in my password manager this time). Thank you!

For the localhost link, it did load localhost. I have something running on my machine at 8080 and clicking the first link took me to the login page for that not anything Jenkins related.

Thanks again!

**Comment by dduportal** [comment]
> For the localhost link, it did load localhost. I have something running on my machine at 8080 and clicking the first link took me to the login page for that not anything Jenkins related.

It was an bug on our side: the link should have been to account.jenkins.io. But now it is fixed.

Thanks for confirming and for your patience!
