### ISSUE TITLE
ci.jenkins.io does not have enough GH permissions to check trust on jenkins-infra/jenkins-codeql

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/helpdesk#3212]
### Service(s)

ci.jenkins.io

### Summary

From https://ci.jenkins.io/job/Infra/computation/console after I added the repo https://github.com/jenkins-infra/jenkins-codeql to the list of scanned repos:

```
Checking pull request [#19](https://github.com/jenkins-infra/jenkins-codeql/pull/19)
ERROR: [Fri Oct 28 12:20:20 UTC 2022] Could not fetch sources from navigator org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator@32fd92a6
[Fri Oct 28 12:20:20 UTC 2022] Finished organization scan. Scan took 16 sec
FATAL: Failed to recompute children of Infra
org.kohsuke.github.HttpException: {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/collaborators/collaborators#get-repository-permissions-for-a-user"}
	at org.kohsuke.github.GitHubConnectorResponseErrorHandler$1.onError(GitHubConnectorResponseErrorHandler.java:56)
	at org.kohsuke.github.GitHubClient.detectKnownErrors(GitHubClient.java:424)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:386)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:355)
	at org.kohsuke.github.Requester.fetch(Requester.java:76)
	at org.kohsuke.github.GHRepository.getPermission(GHRepository.java:1028)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource$1.fetch(GitHubSCMSource.java:1036)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSourceRequest.getPermissions(GitHubSCMSourceRequest.java:450)
	at org.jenkinsci.plugins.github_branch_source.ForkPullRequestDiscoveryTrait$TrustPermission.checkTrusted(ForkPullRequestDiscoveryTrait.java:323)
	at org.jenkinsci.plugins.github_branch_source.ForkPullRequestDiscoveryTrait$TrustPermission.checkTrusted(ForkPullRequestDiscoveryTrait.java:310)
	at jenkins.scm.api.trait.SCMHeadAuthority.isTrusted(SCMHeadAuthority.java:101)
	at jenkins.scm.api.trait.SCMSourceRequest.isTrusted(SCMSourceRequest.java:213)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource$4.create(GitHubSCMSource.java:1270)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource$4.create(GitHubSCMSource.java:1264)
	at jenkins.scm.api.trait.SCMSourceRequest.process(SCMSourceRequest.java:339)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.retrievePullRequest(GitHubSCMSource.java:1261)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.retrieve(GitHubSCMSource.java:1099)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:373)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:327)
	at jenkins.branch.MultiBranchProjectFactory$BySCMSourceCriteria.recognizes(MultiBranchProjectFactory.java:261)
	at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.recognizes(OrganizationFolder.java:1359)
	at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.complete(OrganizationFolder.java:1374)
	at jenkins.scm.api.trait.SCMNavigatorRequest.process(SCMNavigatorRequest.java:254)
	at jenkins.scm.api.trait.SCMNavigatorRequest.process(SCMNavigatorRequest.java:204)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator.visitSources(GitHubSCMNavigator.java:1171)
	at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:536)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:278)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:166)
	at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:918)
	at hudson.model.ResourceController.execute(ResourceController.java:107)
	at hudson.model.Executor.run(Executor.java:449)
Finished: FAILURE
```

This looks like it attempts to look up my permissions for the repo to determine whether I should be able to propose `Jenkinsfile` changes in https://github.com/jenkins-infra/jenkins-codeql/pull/19, but fails to do so for lack of app/token permissions.

**Comment by lemeurherve** [comment]
Not sure what's wrong, I've compared jenkins-codeql settings with the other repos in the same "infra" folder, but didn't found any major difference in term of teams and members permissions, or GitHub apps installed.

Even if it wasn't that, I've tried to add the @jenkins-infra/ci-bot team as writer (like in the accountapp repo), no change (as expected)

I've created some test PRs <sup><sup>[1](https://github.com/jenkins-infra/jenkins-codeql/pull/21), [2](https://github.com/jenkins-infra/jenkins-codeql/pull/22), [3](https://github.com/jenkins-infra/docker-plugin-site-issues/pull/10)</sup></sup> and reproduced the problem, but only on this particular repo: n docker-plugin-site-issues it doesn't failed 🤔 

<details>
<summary>Scan logs</summary>

```console
Examining [jenkins-infra/docker-plugin-site-issues](https://github.com/jenkins-infra/docker-plugin-site-issues)

  Checking branches...

  Getting remote branches...

    Checking branch [main](https://github.com/jenkins-infra/docker-plugin-site-issues/tree/main)

  Getting remote pull requests...
      ‘Jenkinsfile’ found
    Met criteria

  1 branches were processed (query completed)

  1 branches were processed

Finished examining jenkins-infra/docker-plugin-site-issues

Ignoring helpdesk
Ignoring docker-hashicorp-tools
Ignoring digitalocean
Ignoring shared-tools
Proposing jenkins-codeql
Examining [jenkins-infra/jenkins-codeql](https://github.com/jenkins-infra/jenkins-codeql)

  Checking branches...

  Getting remote branches...

    Checking branch [main](https://github.com/jenkins-infra/jenkins-codeql/tree/main)

  Getting remote pull requests...
      ‘Jenkinsfile’ not found
    Does not meet criteria

    Checking branch [classic-markdown](https://github.com/jenkins-infra/jenkins-codeql/tree/classic-markdown)
      ‘Jenkinsfile’ not found
    Does not meet criteria

    Checking branch [csrf](https://github.com/jenkins-infra/jenkins-codeql/tree/csrf)
      ‘Jenkinsfile’ not found
    Does not meet criteria

    Checking branch [lemeurherve-patch-1](https://github.com/jenkins-infra/jenkins-codeql/tree/lemeurherve-patch-1)

    Checking branch [modernize](https://github.com/jenkins-infra/jenkins-codeql/tree/modernize)

    Checking branch [more-more-better-docs](https://github.com/jenkins-infra/jenkins-codeql/tree/more-more-better-docs)
      ‘Jenkinsfile’ not found
    Does not meet criteria

    Checking branch [simpler-phrasing](https://github.com/jenkins-infra/jenkins-codeql/tree/simpler-phrasing)
      ‘Jenkinsfile’ not found
    Does not meet criteria

    Checking branch [unavoidable-impossible](https://github.com/jenkins-infra/jenkins-codeql/tree/unavoidable-impossible)
      ‘Jenkinsfile’ not found
    Does not meet criteria

    Checking branch [unflavored](https://github.com/jenkins-infra/jenkins-codeql/tree/unflavored)
      ‘Jenkinsfile’ not found
    Does not meet criteria

    Checking branch [unsafe-apis](https://github.com/jenkins-infra/jenkins-codeql/tree/unsafe-apis)
      ‘Jenkinsfile’ not found
    Does not meet criteria

  10 branches were processed

  Checking pull-requests...

    Checking pull request [#22](https://github.com/jenkins-infra/jenkins-codeql/pull/22)
ERROR: [Fri Oct 28 13:16:28 UTC 2022] Could not fetch sources from navigator org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator@32fd92a6
[Fri Oct 28 13:16:28 UTC 2022] Finished organization scan. Scan took 15 sec
FATAL: Failed to recompute children of Infra
org.kohsuke.github.HttpException: {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/collaborators/collaborators#get-repository-permissions-for-a-user"}
	at org.kohsuke.github.GitHubConnectorResponseErrorHandler$1.onError(GitHubConnectorResponseErrorHandler.java:56)
	at org.kohsuke.github.GitHubClient.detectKnownErrors(GitHubClient.java:424)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:386)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:355)
	at org.kohsuke.github.Requester.fetch(Requester.java:76)
	at org.kohsuke.github.GHRepository.getPermission(GHRepository.java:1028)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource$1.fetch(GitHubSCMSource.java:1036)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSourceRequest.getPermissions(GitHubSCMSourceRequest.java:450)
	at org.jenkinsci.plugins.github_branch_source.ForkPullRequestDiscoveryTrait$TrustPermission.checkTrusted(ForkPullRequestDiscoveryTrait.java:323)
	at org.jenkinsci.plugins.github_branch_source.ForkPullRequestDiscoveryTrait$TrustPermission.checkTrusted(ForkPullRequestDiscoveryTrait.java:310)
	at jenkins.scm.api.trait.SCMHeadAuthority.isTrusted(SCMHeadAuthority.java:101)
	at jenkins.scm.api.trait.SCMSourceRequest.isTrusted(SCMSourceRequest.java:213)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource$4.create(GitHubSCMSource.java:1270)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource$4.create(GitHubSCMSource.java:1264)
	at jenkins.scm.api.trait.SCMSourceRequest.process(SCMSourceRequest.java:339)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.retrievePullRequest(GitHubSCMSource.java:1261)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.retrieve(GitHubSCMSource.java:1099)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:373)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:327)
	at jenkins.branch.MultiBranchProjectFactory$BySCMSourceCriteria.recognizes(MultiBranchProjectFactory.java:261)
	at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.recognizes(OrganizationFolder.java:1359)
	at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.complete(OrganizationFolder.java:1374)
	at jenkins.scm.api.trait.SCMNavigatorRequest.process(SCMNavigatorRequest.java:254)
	at jenkins.scm.api.trait.SCMNavigatorRequest.process(SCMNavigatorRequest.java:204)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator.visitSources(GitHubSCMNavigator.java:1171)
	at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:536)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:278)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:166)
	at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:918)
	at hudson.model.ResourceController.execute(ResourceController.java:107)
	at hudson.model.Executor.run(Executor.java:449)
Finished: FAILURE
```

</details>

**Comment by daniel-beck** [comment]
As I wrote above, my guess is the app doesn't have permissions to this repo because so far it didn't need it.

Similar issue with an [origin branch](https://ci.jenkins.io/job/Infra/job/jenkins-codeql/view/change-requests/job/PR-20/2/console):

```
00:08:10.117  [GitHub Checks] Failed Publishing GitHub checks: org.kohsuke.github.HttpException: {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/reference/checks#create-a-check-run"}

**Comment by lemeurherve** [comment]
That's what I've just done 🙂

**Comment by lemeurherve** [comment]
I've checked the scan logs, all good now, thanks too @daniel-beck!
