### ISSUE TITLE
Windows agents on ci.jenkins.io disconnect prematurely

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3223]
### Service(s)

ci.jenkins.io

### Summary

The [acceptance test job](https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/check-agent-availability/) that confirms we can allocate agents of multiple types has failed twice in recent operations.  The message in the [log](https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/check-agent-availability/1749/) reports:

```
03:24:03  	aci-maven-8-windows-lg979 was marked offline: Connection was broken: java.nio.channels.ClosedChannelException
03:24:03  	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:241)
03:24:03  	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:221)
03:24:03  	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:825)
03:24:03  	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:289)
03:24:03  	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:177)
03:24:03  	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:279)
03:24:03  	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:501)
03:24:03  	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:244)
03:24:03  	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:196)
03:24:03  	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:209)
03:24:03  	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:793)
03:24:03  	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:172)
03:24:03  	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:343)
03:24:03  	at hudson.remoting.Channel.close(Channel.java:1494)
03:24:03  	at hudson.remoting.Channel.close(Channel.java:1447)
03:24:03  	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:923)
03:24:03  	at hudson.slaves.SlaveComputer$2.run(SlaveComputer.java:803)
03:24:03  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:30)
03:24:03  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:70)
03:24:03  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
03:24:03  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
03:24:03  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
03:24:03  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
03:24:03  	at java.base/java.lang.Thread.run(Thread.java:829)
03:24:03  
03:24:03  [Pipeline] // node
03:24:03  [Pipeline] }
03:24:03  Failed in branch windows
03:24:03  [Pipeline] // parallel
03:24:03  [Pipeline] }
03:24:03  [Pipeline] // stage
03:24:03  [Pipeline] }
03:24:03  [Pipeline] // timeout
03:24:03  [Pipeline] End of Pipeline
03:24:03  java.nio.channels.ClosedChannelException
03:24:03  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 20.241.240.109/20.241.240.109:4033
03:24:03  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
03:24:03  		at hudson.remoting.Request.call(Request.java:199)
03:24:03  		at hudson.remoting.Channel.call(Channel.java:999)
03:24:03  		at hudson.EnvVars.getRemote(EnvVars.java:438)
03:24:03  		at hudson.model.Computer.getEnvironment(Computer.java:1184)
03:24:03  		at org.jenkinsci.plugins.workflow.support.steps.ExecutorStepExecution$PlaceholderTask$PlaceholderExecutable.run(ExecutorStepExecution.java:883)
03:24:03  		at hudson.model.ResourceController.execute(ResourceController.java:107)
03:24:03  		at hudson.model.Executor.run(Executor.java:449)
03:24:03  Also:   hudson.model.Computer$TerminationRequest: Termination requested at Mon Nov 07 10:24:03 UTC 2022 by Thread[Monitoring thread for Response Time started on Mon Nov 07 10:23:33 UTC 2022,5,main] [id=532946]
03:24:03  		at hudson.model.Computer.recordTermination(Computer.java:236)
03:24:03  		at hudson.model.Computer.disconnect(Computer.java:506)
03:24:03  		at hudson.slaves.SlaveComputer.disconnect(SlaveComputer.java:796)
03:24:03  		at hudson.node_monitors.ResponseTimeMonitor$1.monitor(ResponseTimeMonitor.java:77)
03:24:03  		at hudson.node_monitors.AbstractNodeMonitorDescriptor$Record.run(AbstractNodeMonitorDescriptor.java:305)
03:24:03  Caused: hudson.remoting.RequestAbortedException
03:24:03  	at hudson.remoting.Request.abort(Request.java:345)
03:24:03  	at hudson.remoting.Channel.terminate(Channel.java:1080)
03:24:03  	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:241)
03:24:03  	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:221)
03:24:03  	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:825)
03:24:03  	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:289)
03:24:03  	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:177)
03:24:03  	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:279)
03:24:03  	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:501)
03:24:03  	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:244)
03:24:03  	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:196)
03:24:03  	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:209)
03:24:03  	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:793)
03:24:03  	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:172)
03:24:03  	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:343)
03:24:03  	at hudson.remoting.Channel.close(Channel.java:1494)
03:24:03  	at hudson.remoting.Channel.close(Channel.java:1447)
03:24:03  	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:923)
03:24:03  	at hudson.slaves.SlaveComputer$2.run(SlaveComputer.java:803)
03:24:03  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:30)
03:24:03  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:70)
03:24:03  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
03:24:03  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
03:24:03  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
03:24:03  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
03:24:03  	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Reproduction steps

1. Run the acceptance test job that checks agent allocation
2. Confirm that Windows ACI agents are disconnected before their tasks are complete

**Comment by dduportal** [comment]
@MarkEWaite is it only the acceptance test job or do you see the same behavior on other windows agents?

**Comment by MarkEWaite** [comment]
> @MarkEWaite is it only the acceptance test job or do you see the same behavior on other windows agents?

https://ci.jenkins.io/job/Plugins/job/elastic-axis-plugin/job/master/235/console is running as an attempt to confirm that ACI Windows agents are disconnecting for jobs in addition to the simple mode used by the acceptance test.

**Comment by MarkEWaite** [comment]
> > @MarkEWaite is it only the acceptance test job or do you see the same behavior on other windows agents?
> 
> https://ci.jenkins.io/job/Plugins/job/elastic-axis-plugin/job/master/235/console is running as an attempt to confirm that ACI Windows agents are disconnecting for jobs in addition to the simple mode used by the acceptance test.

That test passed, though I assume it may be because the plugin build requests an agent labeled `maven-11-windows` while the acceptance test job requests an agent with label `windows`.  Will need to find a job that uses the agent label `windows`.

**Comment by dduportal** [comment]
> 

The label `windows` should not be used (on my opinion): it is too generic (is it 2019? 2022? another? Which CPU, etc.).

But good catch: we might want to check if any pipeline/library uses it.

**Comment by dduportal** [comment]
@smerle33 starts working on cleaning up the `windows` label.

**Comment by dduportal** [comment]
Last step: update acceptance test job to stop checking this label (and check the "new real ones".

**Comment by dduportal** [comment]
Closing: https://github.com/jenkins-infra/acceptance-tests/pull/34 is green and merged.
