### ISSUE TITLE
Various plugin downloads fails with HTTP response 500

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3282]
### Service(s)

Update center

### Summary

I was going ahead and update a few plugins, but various ones failed to download:

```
java.io.IOException: Server returned HTTP response code: 500 for URL: https://get.jenkins.io/plugins/workflow-cps/3565.v4b_d9b_8c29a_b_3/workflow-cps.hpi
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1585)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1296)
Caused: java.io.IOException: Failed to load https://updates.jenkins.io/download/plugins/workflow-cps/3565.v4b_d9b_8c29a_b_3/workflow-cps.hpi to /Users/alex/.jenkins/plugins/workflow-cps.jpi.tmp
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1307)
Caused: java.io.IOException: Failed to download from https://updates.jenkins.io/download/plugins/workflow-cps/3565.v4b_d9b_8c29a_b_3/workflow-cps.hpi (redirected to: https://get.jenkins.io/plugins/workflow-cps/3565.v4b_d9b_8c29a_b_3/workflow-cps.hpi)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1341)
	at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1898)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2210)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1872)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:121)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

![Screenshot 2022-12-06 at 14 07 38](https://user-images.githubusercontent.com/13383509/205920904-353cca4d-eaf0-4da0-bb26-b0afea9b2834.png)

Accessing one of the failing URLs in the browser, e.g. https://get.jenkins.io/plugins/workflow-cps/3565.v4b_d9b_8c29a_b_3/workflow-cps.hpi, returns `redigo: nil returned`.

**Comment by lemeurherve** [comment]
Strange, I've just tested downloading from these links in my browser, no issue.

**Comment by lemeurherve** [comment]
Can you give us some failed build links please?

**Comment by timja** [comment]
likely a local mirror issue

**Comment by lemeurherve** [comment]
It closely happened as the same time as I was decommissioning [gruenehoelle.nl mirror](https://github.com/jenkins-infra/helpdesk/issues/3281), maybe related?

**Comment by lifeofguenter** [comment]
FWIW: I have not decommissioned https://mirror.gruenehoelle.nl/jenkins/ yet on my side, so it should still be functional.

**Comment by dduportal** [comment]
> likely a local mirror issue

Weird: the error message explcitly mentions get.jenkins.io: I would have expected a mirror issue to be reported with the underlying mirror URL (destination of the HTTP/302).

I guess the correlation with the removal of the gruenehoelle mirror inside get.jenkins.io could explain the behavior.

@NotMyFault do you still have the issue?

**Comment by dduportal** [comment]
Closing as the HTTP/500 were mirrorbits (mirror redirector service error at `get.jenkins.io`) when we removed the mirror.

No more error, and I was able to reproduce the behavior on a local instance of mirrorbit.
