### ISSUE TITLE
javadoc build is failing (`zdevops.jar` is not a valid ZIP file)

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3290]
### Service(s)

Other

### Summary

The job, in trusted.ci.jenkins.io, in charge of building the [Jenkins Javadocs](https://github.com/jenkins-infra/javadoc) failed the 12 of December 2022.

The error message is the following:

```text
06:27:53  Publishing plugin zdevops
06:27:53      [unzip] Expanding: /home/jenkins/workspace/javadoc/build/site/plugin/zdevops/zdevops.jar into /home/jenkins/workspace/javadoc/build/site/plugin/zdevops
06:27:53  Caught: : Error while expanding /home/jenkins/workspace/javadoc/build/site/plugin/zdevops/zdevops.jar
06:27:53  java.util.zip.ZipException: archive is not a ZIP archive
06:27:53  : Error while expanding /home/jenkins/workspace/javadoc/build/site/plugin/zdevops/zdevops.jar
06:27:53  java.util.zip.ZipException: archive is not a ZIP archive
06:27:53  	at org.apache.tools.ant.taskdefs.Expand.expandFile(Expand.java:190)
06:27:53  	at org.apache.tools.ant.taskdefs.Expand.execute(Expand.java:132)
06:27:53  	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
06:27:53  	at jdk.internal.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
06:27:53  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:27:53  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
06:27:53  	at JavadocGroupBuilder.withArtifact(JavadocGroupBuilder.groovy:84)
06:27:53  	at JavadocGroupBuilder$withArtifact$0.callCurrent(Unknown Source)
06:27:53  	at JavadocGroupBuilder.withArtifact(JavadocGroupBuilder.groovy:39)
06:27:53  	at JavadocGroupBuilder$withArtifact.call(Unknown Source)
06:27:53  	at generate-javadoc-plugins$_run_closure3.doCall(generate-javadoc-plugins.groovy:28)
06:27:53  	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
06:27:53  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:27:53  	at generate-javadoc-plugins.run(generate-javadoc-plugins.groovy:26)
06:27:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
06:27:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
06:27:53  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:27:53  Caused by: java.util.zip.ZipException: archive is not a ZIP archive
06:27:53  	at org.apache.tools.zip.ZipFile.positionAtEndOfCentralDirectoryRecord(ZipFile.java:771)
06:27:53  	at org.apache.tools.zip.ZipFile.positionAtCentralDirectory(ZipFile.java:707)
06:27:53  	at org.apache.tools.zip.ZipFile.populateFromCentralDirectory(ZipFile.java:452)
06:27:53  	at org.apache.tools.zip.ZipFile.<init>(ZipFile.java:214)
06:27:53  	at org.apache.tools.ant.taskdefs.Expand.expandFile(Expand.java:168)
06:27:53  	... 16 more
06:27:53  [Pipeline] }
06:27:53  [Pipeline] // withEnv
06:27:53  [Pipeline] }
06:27:53  [Pipeline] // stage
06:27:53  [Pipeline] }
06:27:53  [Pipeline] // node
06:27:53  [Pipeline] End of Pipeline
06:27:53  ERROR: script returned exit code 1
06:27:53  Finished: FAILURE
```

- Root cause has to be diagnosed and identified (the message looks obvious but it has to be verified and confirmed to have a direct actionnable for fixing)
- The plugin zdevops is brand new: https://github.com/jenkins-infra/helpdesk/issues/3279 . We have to give clear and kind directions to the maintainer as they got started recently.

**Comment by dduportal** [comment]
- The issue is also visible publicly at https://ci.jenkins.io/job/Infra/job/javadoc/job/master/388/console
- Root cause is that the javadocs JAR artefact exists for zdevops 1.0.0 but.. is empty: https://repo.jenkins-ci.org/artifactory/public/io/jenkins/plugins/zdevops/1.0.0/zdevops-1.0.0-javadoc.jar

**Comment by dduportal** [comment]
Hello @IBA-mainframe-dev, could you check on your own that the manual release is not empty for you?

On artifactory, the file is sized at 0 bytes: something went wrong during the initial release and you might need to cut a 1.0.1 release with the correct artefacts

**Comment by MarkEWaite** [comment]
I confirmed that the build passed on trusted.ci.jenkins.io when I ran it there after the fix in https://github.com/jenkins-infra/javadoc/pull/56
