### ISSUE TITLE
Null pointer exception on stable-2.387 CI job

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3386]
### Service(s)

ci.jenkins.io

### Summary

The [stable-2.387 branch](https://ci.jenkins.io/job/Core/job/jenkins/job/stable-2.387/4/) on ci.jenkins.io is reporting a null pointer exception as it ends.

```
03:23:22  [Pipeline] End of Pipeline
03:23:22  java.lang.NullPointerException: Cannot invoke method replace() on null object
03:23:22  	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
03:23:22  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
03:23:22  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
03:23:22  	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
03:23:22  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
03:23:22  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
03:23:22  	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
03:23:22  	at infra.withArtifactCachingProxy(infra.groovy:127)
03:23:22  	at ___cps.transform___(Native Method)
```

### Reproduction steps

1. Open the build log and confirm it is reporting a null pointer exception

**Comment by lemeurherve** [comment]
This is due to the replay I've started to test https://github.com/jenkins-infra/pipeline-library/pull/592, which is a WIP.

The previous "normal" build on this branch is OK.
