### ISSUE TITLE
EC2s are not available

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3421]
### Service(s)

ci.jenkins.io, infra.ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io

### Summary

All EC2 instances of the services mentioned are offline :(
```
java.io.EOFException
	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2911)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3406)
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:932)
	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:375)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
	at hudson.remoting.Command.readFrom(Command.java:142)
	at hudson.remoting.Command.readFrom(Command.java:128)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:61)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:75)
```

### Reproduction steps

Have mercy on me and the number of issues I'm submitting this week 🙃

**Comment by dduportal** [comment]
It's weird: the EC2 agents are working as expected, BUT seems to be kept in a "broken" state.

- The idleTermination time is set to 30 min: has we use spot instance, for sure the instance might be reclaimed before the next "garbage collection of EC2 agents in the next 30 min". Gotta open a PR and see if it helps.
- Gotta check the credential expiration (just in case)

**Comment by dduportal** [comment]
- Credentials are OK
- IdleTermination time is 1 minute now

=> let's see the result tomorrow. If still the case, then we'll check the evicted spot policies.

**Comment by dduportal** [comment]
Update:

- The idleTermination parameter at "1 minute" works as expected *but only on the EC2 agents created after applying the configuration*
- We've been alerted that the AWS billing this month (March 2023) is out of limits (forcasted 22k€ instead of ~11k€)

![Capture d’écran 2023-03-21 à 10 13 46](https://user-images.githubusercontent.com/1522731/226573050-ea151b04-c3c3-4496-96bf-684ea5f206f5.png)

- We saw a bunch of EC2 agent VMs created between the 18 and the 20 of March (+ some the 21 but being handled properly with the new idleTermination). These agents were marked as "Connection Broken" as this issue is about.
  - We've manually deleted these VMs from EC2's interface.
  - 3 minutes later, ci.jenkins.io removed the associated (broken) agent (another formal proof of the effect of idelTerminationTimeout)

**Comment by dduportal** [comment]
We are gathering interesting metrics about the usage increase on AWS (gotta report below).

However, as a drastic measure for March 2023, we'll remove/decrease the EC2 VM agent usages from the infrastructure:

- ci.jenkins.io 
  - Removal of all EC2 VM agents except the `linux-arm64` (Azure VM agents are set up to provide Linux-x86, Linux-Highmem-x86, and Windows-*-x86 agents)
  - Decreasing the `cik8s` Kubernetes cloud usage (as we have also have the `doks` in DigitalOcean) from `150` maximum pod agents to `30`

- infra.ci.jenkins.io: full switch to Azure VM agents, no need to stick the AWS for this controller which runs in an Azure Kubernetes

We'll also decrease the maximum size of the Kuber

**Comment by smerle33** [comment]
added an azure cloud in infra.ci and started to implement azure vm template ... to be continued to have the same set as on aws ...

**Comment by smerle33** [comment]
Those AWS Vms have been removed from infra.ci : 

- AMD64 Ubuntu 20.04
- AMD64 Ubuntu 20.04 Big
- Windows 2019 AMD64

(we keep ARM64 Ubuntu 20.04 for now)

Those Azure Vms have been added to infra.ci : 

- AMD64 Ubuntu 20.04
- Windows 2019 AMD64
