### ISSUE TITLE
plugins.jenkins.io is missing recent releases

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3447]
### Service(s)

plugins.jenkins.io

### Summary

The warnings next generation plugin and a number of related plugins released a day ago but they are not visible on https://plugins.jenkins.io/warnings-ng/releases/ 

The warnings next generation plugin should be 10.0.2 but it shows a 9.x as the most recent release.

https://get.jenkins.io/plugins/warnings-ng/10.0.2/warnings-ng.hpi?mirrorlist shows that the 1.0.2 version is mirrored around the world but it is not visible on the plugins site

### Reproduction steps

1. Confirm that warnings ng 10.0.2 is visible on the mirrors at https://get.jenkins.io/plugins/warnings-ng/10.0.2/warnings-ng.hpi?mirrorlist but is not visible at https://plugins.jenkins.io/warnings-ng/releases/

**Comment by NotMyFault** [comment]
The job on infra.ci is failing since Monday:
```
[2023-03-13T18:18:19.285Z] Traceback (most recent call last):
[2023-03-13T18:18:19.285Z]   File "/usr/local/bin/blobxfer", line 5, in <module>
[2023-03-13T18:18:19.285Z]     from blobxfer_cli.cli import cli
[2023-03-13T18:18:19.285Z]   File "/usr/local/lib/python3.9/dist-packages/blobxfer_cli/cli.py", line 34, in <module>
[2023-03-13T18:18:19.285Z]     import blobxfer.api
[2023-03-13T18:18:19.285Z]   File "/usr/local/lib/python3.9/dist-packages/blobxfer/api.py", line 30, in <module>
[2023-03-13T18:18:19.285Z]     from .operations.azure.blob.append import (  # noqa
[2023-03-13T18:18:19.285Z]   File "/usr/local/lib/python3.9/dist-packages/blobxfer/operations/azure/__init__.py", line 35, in <module>
[2023-03-13T18:18:19.285Z]     import blobxfer.operations.azure.blob.append
[2023-03-13T18:18:19.285Z]   File "/usr/local/lib/python3.9/dist-packages/blobxfer/operations/azure/blob/__init__.py", line 29, in <module>
[2023-03-13T18:18:19.285Z]     import azure.storage.blob.models
[2023-03-13T18:18:19.285Z]   File "/usr/local/lib/python3.9/dist-packages/azure/storage/blob/__init__.py", line 6, in <module>
[2023-03-13T18:18:19.285Z]     from .appendblobservice import AppendBlobService
[2023-03-13T18:18:19.285Z]   File "/usr/local/lib/python3.9/dist-packages/azure/storage/blob/appendblobservice.py", line 43, in <module>
[2023-03-13T18:18:19.285Z]     from .baseblobservice import BaseBlobService
[2023-03-13T18:18:19.285Z]   File "/usr/local/lib/python3.9/dist-packages/azure/storage/blob/baseblobservice.py", line 34, in <module>
[2023-03-13T18:18:19.285Z]     from azure.storage.common._error import (
[2023-03-13T18:18:19.285Z] ImportError: cannot import name '_validate_user_delegation_key' from 'azure.storage.common._error' (/usr/local/lib/python3.9/dist-packages/azure/storage/common/_error.py)
```

**Comment by lemeurherve** [comment]
FTR, [the last update of jenkins-infra/docker-builder image version](https://github.com/jenkins-infra/plugin-site/pull/1300) broke the build, [again](https://github.com/jenkins-infra/plugin-site/pull/1284) 🙁

Currently [looking at the difference](https://github.com/jenkins-infra/docker-builder/compare/2.0.55...2.2.25), I'll check if I can replace blobxfer by az-cli, and will revert renovate PR if not.

**Comment by lemeurherve** [comment]
As explained in https://github.com/jenkins-infra/docker-builder/pull/126, the `python3-dev` dependency needed to install `azure-cli` with `pip3` broke `blobxfer`, switching to the debian package for `azure-cli` installation fixed it.
