### ISSUE TITLE
[ci.jenkins.io] Use Artifact Manager to store archived artifacts (and stashes)

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3496]
_Originally posted by @dduportal in https://github.com/jenkins-infra/helpdesk/issues/3492#issuecomment-1499315898_
            
Let's use an Azure Blob storage to store archived artifacts for ci.jenkins.io (instead of using its data disk)

- Install the [Azure Artifact Manager](https://plugins.jenkins.io/azure-artifact-manager/) plugin
- Define Azure resources (storage account, blob storage, blob credential) in jenkins-infra/azure Terraform project
- Announce operation to the developer mailing list as it could break the usage of `stash` and `unstash` keyword
- Set up ci.jenkins.io with JCasc to use this storage account
- Verify with a pipeline (`archiveArtifacts`, `stash` and `unstash`)

Please note that it could help for https://github.com/jenkins-infra/helpdesk/issues/3485

**Comment by dduportal** [comment]
First configuration to try during the week-end:

- Reusing the existing storage account `prodjenkinscistore`
- Rotated the keys and configured the 2nd key in ci.jenkins as the "storage account" (credential kind)
- Configured a new blob storage `prodjenkinsciartifacts` 

- After a few minutes, I see content in the blob storage ✅ 
- Trying for instance the PR https://ci.jenkins.io/job/Plugins/job/sauce-ondemand-plugin/view/change-requests/job/PR-115/: it archived successfully and a tentative download redirects to the blobstorage system:

```
$ curl -v -o /dev/null -s https://ci.jenkins.io/job/Plugins/job/sauce-ondemand-plugin/view/change-requests/job/PR-115/lastSuccessfulBuild/artifact/org/jenkins-ci/plugins/sauce-ondemand/1.213-rc1132.f5e0495fb_a_ca/sauce-ondemand-1.213-rc1132.f5e0495fb_a_ca-javadoc.jar
*   Trying 104.208.238.39:443...
* Connected to ci.jenkins.io (104.208.238.39) port 443 (#0)
# ...
> GET /job/Plugins/job/sauce-ondemand-plugin/view/change-requests/job/PR-115/lastSuccessfulBuild/artifact/org/jenkins-ci/plugins/sauce-ondemand/1.213-rc1132.f5e0495fb_a_ca/sauce-ondemand-1.213-rc1132.f5e0495fb_a_ca-javadoc.jar HTTP/2
> Host: ci.jenkins.io
> user-agent: curl/7.87.0
> accept: */*
> 
< HTTP/2 302 
< date: Fri, 14 Apr 2023 18:08:25 GMT
< server: Jetty(10.0.13)
< x-content-type-options: nosniff
< location: https://prodjenkinscistore.blob.core.windows.net/prodjenkinsciartifacts/Plugins%2Fsauce-ondemand-plugin%2FPR-115%2F1%2Fartifacts%2Forg%2Fjenkins-ci%2Fplugins%2Fsauce-ondemand%2F1.213-rc1132.f5e0495fb_a_ca%2Fsauce-ondemand-1.213-rc1132.f5e0495fb_a_ca-javadoc.jar?sv=2021-06-08&se=2023-04-14T19%3A08%3A25Z&sr=b&sp=r&sig=h29kk2yhbmE43bofx1RimyDQ8BQbFZwAY6SZXeNdaC8%3D
< content-length: 0
< via: 2.0 ci.jenkins.io
< content-type: application/java-archive
< 
{ [0 bytes data]
* Connection #0 to host ci.jenkins.io left intact
```


Looks like it's working very well!

**Comment by dduportal** [comment]
Next steps before closing:

- [ ] Import the storage account + blob storage into terraform
- [ ] Add the JCasc configuration for ci.jenkins.io

**Comment by dduportal** [comment]
Removed the configuration because it fails builds (but not all):

- https://github.com/jenkinsci/bom/pull/1965#issuecomment-1509469723
- https://github.com/jenkins-infra/helpdesk/issues/3516

**Comment by dduportal** [comment]
After a quick diagnostic:

- The storage account used for the blob storage did not have the expected configuration, because it was created years ago:
  - TLS/HTTPS setup was not good enough
  - It was an old "General Purpose v1" system
  - We only need Blob storage, while other services were enabled (file sharing, queue, etc.)
  - Pubic access was not enabled

- All the failing builds have an error stack, at the end of build log (but nothing on the system logs!), like the following:

```
io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
    at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2113)
    at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Also:   java.lang.Exception: #block terminated with an error
            at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
Caused: reactor.core.Exceptions$ReactiveException
    at reactor.core.Exceptions.propagate(Exceptions.java:392)
    at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
    at reactor.core.publisher.Mono.block(Mono.java:1707)
    at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:191)
    at com.azure.storage.blob.BlobClient.uploadFromFileWithResponse(BlobClient.java:473)
    at com.microsoftopentechnologies.windowsazurestorage.service.UploadService$UploadThread.call(UploadService.java:426)
    at com.microsoftopentechnologies.windowsazurestorage.service.UploadService$UploadThread.call(UploadService.java:387)
    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
Caused: java.util.concurrent.ExecutionException
    at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
    at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
    at com.microsoftopentechnologies.windowsazurestorage.service.UploadService$UploadOnSlave.invoke(UploadService.java:323)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ec2-3-143-84-83.us-east-2.compute.amazonaws.com/3.143.84.83:33447
            at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
            at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
            at hudson.remoting.Channel.call(Channel.java:1000)
            at hudson.FilePath.act(FilePath.java:1192)
            at hudson.FilePath.act(FilePath.java:1181)
            at com.microsoftopentechnologies.windowsazurestorage.service.UploadToBlobService.uploadIndividuals(UploadToBlobService.java:133)
            at com.microsoftopentechnologies.windowsazurestorage.service.UploadService.execute(UploadService.java:527)
            at com.microsoft.jenkins.artifactmanager.AzureArtifactManager.stash(AzureArtifactManager.java:427)
            at org.jenkinsci.plugins.workflow.flow.StashManager.stash(StashManager.java:118)
            at org.jenkinsci.plugins.workflow.support.steps.stash.StashStep$Execution.run(StashStep.java:119)
            at org.jenkinsci.plugins.workflow.support.steps.stash.StashStep$Execution.run(StashStep.java:107)
            at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
            at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:829)
Caused: java.io.IOException
    at com.microsoftopentechnologies.windowsazurestorage.service.UploadService$UploadOnSlave.invoke(UploadService.java:326)
    at com.microsoftopentechnologies.windowsazurestorage.service.UploadService$UploadOnSlave.invoke(UploadService.java:295)
    at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3578)
    at hudson.remoting.UserRequest.perform(UserRequest.java:211)
    at hudson.remoting.UserRequest.perform(UserRequest.java:54)
    at hudson.remoting.Request$2.run(Request.java:377)
    at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:125)
    at java.base/java.lang.Thread.run(Unknown Source)
Caused: com.microsoftopentechnologies.windowsazurestorage.exceptions.WAStorageException: Fail to upload individual files to blob
    at com.microsoftopentechnologies.windowsazurestorage.service.UploadToBlobService.uploadIndividuals(UploadToBlobService.java:138)
    at com.microsoftopentechnologies.windowsazurestorage.service.UploadService.execute(UploadService.java:527)
    at com.microsoft.jenkins.artifactmanager.AzureArtifactManager.stash(AzureArtifactManager.java:427)
Caused: java.io.IOException
    at com.microsoft.jenkins.artifactmanager.AzureArtifactManager.stash(AzureArtifactManager.java:430)
    at org.jenkinsci.plugins.workflow.flow.StashManager.stash(StashManager.java:118)
    at org.jenkinsci.plugins.workflow.support.steps.stash.StashStep$Execution.run(StashStep.java:119)
    at org.jenkinsci.plugins.workflow.support.steps.stash.StashStep$Execution.run(StashStep.java:107)
    at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
[2023-04-14T20:20:29.867Z] [GitHub Checks] GitHub check (name: Jenkins, status: completed) has been published.
[2023-04-14T20:20:29.881Z] Finished: FAILURE
```

- All the "success" builds (e.g. build able to stash or archive artifacts with success to the blob) all have a common point: they use an Azure VM agent (label `docker` for instance), while the failing builds are running in containers (in AWS or DigitalOcean) which maps with the missing "public" access feature of the storage account

**Comment by dduportal** [comment]
- Created a new storageaccount `cijenkinsioartifacts`, of type v2, hot storage but no replication (LRS) and no versoning to keep cost as low as posible, with only the bare minimum services (blob, HTTPS) and public access enabled.
- Let's retry and verify with a  `bom` build if the stash happens without error. If it does, let's communicate to users

**Comment by dduportal** [comment]
- Removed the configuration as the error is still the same even with the new blob setup. Gotta reproduce locally

**Comment by dduportal** [comment]
Opened an issue on the plugin repository (cc @timja if you have memories of the plugin internals)

**Comment by jglick** [comment]
> failure as well

FWIW https://github.com/jenkinsci/aws-global-configuration-plugin/pull/60

**Comment by dduportal** [comment]
> Why? All I did in https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/388 is make it clearer in error messages that you have a nonsensical configuration: no credentials specified, so implicitly assuming instance/workload identity, yet explicitly suppressing session credentials which that mode would require.

Sorry, I misunderstood as I only checked superficially the messages. It make sense thanks!

**Comment by dduportal** [comment]
As per the discussions in https://github.com/jenkinsci/bom/pull/1969#issuecomment-1515909374, it seems that using a legit AWS S3 bucket with the S3 Artifact Manager is the proposed trade-off:

- S3 costs: If we assume 500 Gb of Artifacts and stashes, it means ~ 11$ per month with a Standard S3 https://aws.amazon.com/s3/pricing/
  - The requests are also billed, so it's hard to tell but for ~100$ we should be able to get 250.000 requests per month roughly

- The `bom` build would benefit from using AWS S3 (close to their network):
  - We could , again, use stash/unstash of the megaWar on the `bom` build and avoid spending expansive compute time, without suffering from network delays
  - Should still decrease the outbound bandwidth for the ci.jenkins.io VM
  - Impact would be added outbound bandwidth from Azure agents (VMs) but since we spread across 3 clouds, we do not have a solution

**Comment by jglick** [comment]
Just let me know how you want to proceed. I could revert https://github.com/jenkinsci/bom/pull/1955 (excepting some cleanups I did along the way).

**Comment by dduportal** [comment]
> Just let me know how you want to proceed. I could revert [jenkinsci/bom#1955](https://github.com/jenkinsci/bom/pull/1955) (excepting some cleanups I did along the way).

Are you ok to revert now?

That would allow us to merge (unless something else is not working) https://github.com/jenkinsci/bom/pull/1969#issuecomment-1515909374 to benefit from separating `bom` build from other builds (and decreasing the credit consumption in DigitalOcean + avoid plugin developers to wait when there is a BOM build)

**Comment by jglick** [comment]
> Are you ok to revert now?

I can try to prepare such a PR though it is not a trivial revert since there are some things I want to keep. Kind of busy; maybe I can get to it today, maybe next week.

**Comment by dduportal** [comment]
> > Are you ok to revert now?
> 
> I can try to prepare such a PR though it is not a trivial revert since there are some things I want to keep. Kind of busy; maybe I can get to it today, maybe next week.

ack, many thanks for helping on this topic!

**Comment by dduportal** [comment]
Enabling the S3 Artifact Manager for ci.jenkins.io:

- S3 bucket (etc. al) resource management in Terraform: https://github.com/jenkins-infra/aws/pull/395
- Enabling S3 Artifact Manager config in JCasc configuration: https://github.com/jenkins-infra/jenkins-infra/pull/2782

**Comment by dduportal** [comment]
- Fixup on https://github.com/jenkins-infra/jenkins-infra/pull/2783
- Checked with a build of plugin-jenkins-infra-test
- We see data in the S3 bucket now
- Let's go for the BOM in https://github.com/jenkinsci/bom/pull/1969

Keepin the issue open for the week end

**Comment by dduportal** [comment]
- No error found in the system logs
- No issue reported by developers
- The BOM builds in https://github.com/jenkinsci/bom/pull/1969 shows slower time in the stash/unstash

There was clearly impacts with @jglick initial change in the bom, and now with this change:

<img width="1723" alt="Capture d’écran 2023-04-24 à 12 22 53" src="https://user-images.githubusercontent.com/1522731/233970215-845eed0a-a9ae-4fd9-bc57-804176616446.png">

This issue can be closed:

- S3 Artifact seems good
- Removed the (unused) Storage accounts in Azure's resource group `prodjenkinsci`
- Removed the "Azure Artifact Manager" plugin from ci.jenkins.io, along with the (unused) storage account credential
- Benefits from `bom` builds (at least!) is established
- Costs will be checked in #3502 for AWS S3 cost and in #3485 for Azure outbound bandwidth decrease
