### ISSUE TITLE
Can't access applitools account

### ISSUE THREAD

**Issue by itaibh** [jenkins-infra/helpdesk#3564]
### Type(s) of account issue

I've lost my password

### Summary

I have an old password to the username `applitools` which doesn't work anymore. It was last updated in 2020 from something else.
I tried clicking on the "Forgot password" link in the accounts.jenkins.io page, and the following had happened:

1. When I tried using `applitools` as a username, I got a server error (see below).
2. When I tried using several company emails I got a message claiming that "_If your user account or email address exists in our database, you will receive a password at your email address in a few minutes_" but no email was received in any of them.

---

The server error I got when I used `applitools` as a username:

<h2 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP ERROR 500 javax.servlet.ServletException: jakarta.mail.SendFailedException: Invalid Addresses; nested exception is: com.sun.mail.smtp.SMTPAddressFailedException: 501 Invalid command or cannot parse to address</h2>

URI: | /doPasswordReset
-- | --
500
javax.servlet.ServletException: jakarta.mail.SendFailedException: Invalid Addresses; nested exception is: com.sun.mail.smtp.SMTPAddressFailedException: 501 Invalid command or cannot parse to address
Stapler
javax.servlet.ServletException: jakarta.mail.SendFailedException: Invalid Addresses; nested exception is: com.sun.mail.smtp.SMTPAddressFailedException: 501 Invalid command or cannot parse to address
jakarta.mail.SendFailedException: Invalid Addresses; nested exception is: com.sun.mail.smtp.SMTPAddressFailedException: 501 Invalid command or cannot parse to address
com.sun.mail.smtp.SMTPAddressFailedException: 501 Invalid command or cannot parse to address

<h3 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Caused by:</h3><pre style="color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">javax.servlet.ServletException: jakarta.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 Invalid command or cannot parse to address

	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:818)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:900)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:698)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:248)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1410)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:170)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1385)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1307)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:149)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: jakarta.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 Invalid command or cannot parse to address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:2064)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1286)
	at jakarta.mail.Transport.send0(Transport.java:231)
	at jakarta.mail.Transport.send(Transport.java:100)
	at org.jenkinsci.account.Application.mail(Application.java:263)
	at org.jenkinsci.account.Application$User.mailPasswordReset(Application.java:423)
	at org.jenkinsci.account.Application.doDoPasswordReset(Application.java:343)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:397)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:409)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:207)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:140)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:558)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:59)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:770)
	... 43 more
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 Invalid command or cannot parse to address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1917)
	... 57 more
</pre><hr style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://eclipse.org/jetty" style="font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;">Powered by Jetty:// 10.0.14</a><hr style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP ERROR 500 javax.servlet.ServletException: jakarta.mail.SendFailedException: Invalid Addresses; nested exception is: com.sun.mail.smtp.SMTPAddressFailedException: 501 Invalid command or cannot parse to address
URI:	/doPasswordReset
STATUS:	500
MESSAGE:	javax.servlet.ServletException: jakarta.mail.SendFailedException: Invalid Addresses; nested exception is: com.sun.mail.smtp.SMTPAddressFailedException: 501 Invalid command or cannot parse to address
SERVLET:	Stapler
CAUSED BY:	javax.servlet.ServletException: jakarta.mail.SendFailedException: Invalid Addresses; nested exception is: com.sun.mail.smtp.SMTPAddressFailedException: 501 Invalid command or cannot parse to address
CAUSED BY:	jakarta.mail.SendFailedException: Invalid Addresses; nested exception is: com.sun.mail.smtp.SMTPAddressFailedException: 501 Invalid command or cannot parse to address
CAUSED BY:	com.sun.mail.smtp.SMTPAddressFailedException: 501 Invalid command or cannot parse to address
Caused by:
javax.servlet.ServletException: jakarta.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 Invalid command or cannot parse to address

	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:818)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:900)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:698)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:248)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1410)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:170)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1385)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1307)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:149)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: jakarta.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 Invalid command or cannot parse to address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:2064)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1286)
	at jakarta.mail.Transport.send0(Transport.java:231)
	at jakarta.mail.Transport.send(Transport.java:100)
	at org.jenkinsci.account.Application.mail(Application.java:263)
	at org.jenkinsci.account.Application$User.mailPasswordReset(Application.java:423)
	at org.jenkinsci.account.Application.doDoPasswordReset(Application.java:343)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:397)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:409)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:207)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:140)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:558)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:59)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:770)
	... 43 more
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 Invalid command or cannot parse to address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1917)
	... 57 more
[Powered by Jetty:// 10.0.14](https://eclipse.org/jetty)

### jenkins.io account username

applitools

### Which URL are you trying to login at?

https://accounts.jenkins.io/login

https://repo.jenkins-ci.org/

**Comment by itaibh** [comment]
The automated reply doen't help. I looked at the ticket there. I don't think it's the same case.

**Comment by lemeurherve** [comment]
@itaibh there was an issue with the email associated with the `applitools` Jenkins user (it was incomplete), hence the error you've encountered.

I've set it to the same email as the one associated with the `applitools` Jira user, and triggered a password reset, there should be a corresponding email in that mailbox.

Could you confirm us you received it?

**Comment by itaibh** [comment]
I did. Thank you.

**Comment by itaibh** [comment]
How long does it take from deployment until I see the new plugin version in the list?

**Comment by lemeurherve** [comment]
It can go up to 2~3 hours

**Comment by itaibh** [comment]
@lemeurherve I can access the account now, but the curl is returning 401, and in JFrog's artifactory "set me up" doesn't return any value (it also doesn't look anything like the docs, I did my best to select the correct things).

**Comment by dduportal** [comment]
This account was an "old" one and inherited from unexpected settings when Keycloak was introduced in 2020.

Applied the 2 following changes:

- In keycloak, removed the "Verified Email" required action and set the email as verified.
- In artifactory, updated the user configuration to "Disable Internal password".

=> as verified in IRC with @itaibh , it allowed to succesfully run the `curl` command at https://www.jenkins.io/doc/developer/publishing/releasing-manually/#using-curl

**Comment by itaibh** [comment]
this is the `~/.m2/settings.xml` minus comments and passwords:

```
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
    <pluginGroups>
</pluginGroups>
    <proxies>
</proxies>
    <servers>

        <server>
            <id>ossrh</id>
            <username>b3RFNvsd</username>
            <password>...</password>
        </server>
        <server>
            <id>maven.jenkins-ci.org</id> <!-- For parent 1.397 or newer; before this use id java.net-m2-repository -->
            <username>applitools</username>
            <password>...</password>
        </server>
        <server>
            <id>repo.jenkins-ci.org</id> <!-- For parent 1.397 or newer; before this use id java.net-m2-repository -->
            <username>applitools</username>
            <password>...</password>
        </server>
        <server>
            <id>jfrog</id>
            <username>java5-deployer</username>
            <password>...</password>
        </server>
    </servers>
    <mirrors>
    </mirrors>
    <profiles>
        <profile>
            <id>local-build-declarations</id>
            <properties>
                <gpg.keyname>...</gpg.keyname>
                <gpg.passphrase>...</gpg.passphrase>
                <local.build>true</local.build>
            </properties>
        </profile>

        <profile>
            <id>allow-snapshots</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <repositories>
                <repository>
                    <id>snapshots-repo</id>
                    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
                    <releases>
                        <enabled>false</enabled>
                    </releases>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                </repository>
            </repositories>
        </profile>

        <profile>
            <id>bamboo-build</id>
            <repositories>
                <repository>
                    <id>atlassian-public</id>
                    <url>https://m2proxy.atlassian.com/repository/public</url>
                    <snapshots>
                        <enabled>true</enabled>
                        <updatePolicy>daily</updatePolicy>
                        <checksumPolicy>warn</checksumPolicy>
                    </snapshots>
                    <releases>
                        <enabled>true</enabled>
                        <checksumPolicy>warn</checksumPolicy>
                    </releases>
                </repository>
            </repositories>

            <pluginRepositories>
                <pluginRepository>
                    <id>atlassian-public</id>
                    <url>https://m2proxy.atlassian.com/repository/public</url>
                    <releases>
                        <enabled>true</enabled>
                        <checksumPolicy>warn</checksumPolicy>
                    </releases>
                    <snapshots>
                        <checksumPolicy>warn</checksumPolicy>
                    </snapshots>
                </pluginRepository>
            </pluginRepositories>
        </profile>
    </profiles>
    <activeProfiles>
        <activeProfile>local-build-declarations</activeProfile>
        <activeProfile>allow-snapshots</activeProfile>
    </activeProfiles>
</settings>
```

**Comment by dduportal** [comment]
On Artifactory side, there is no error related to your tentatives: it means that you have to debug the Maven calls as the  HTTP/401 clearly means the password is not sent as expected by Maven.

@itaibh Could you try the followings:

-Reducing the settings file to its minimum (e.g. only the content retrived from Artifactory by the `curl` command) and/or try with a `mvn -s minimalist-settings.xml #...` command)?
- Ensure you are using the latest Maven 3.9.x version available for your platform?
- Retry with the plugins pom parent 4.62 (last stable version) to ensure any used maven release plugin is up to date through the parent? (ref. https://github.com/jenkinsci/plugin-pom/compare/plugin-4.51...plugin-4.62)?

**Comment by itaibh** [comment]
I removed the `<distribution>` segment and the build/deploy passed. Still I don't see the updated package. I was told it could take up to 2 hours. Is that so?

**Comment by dduportal** [comment]
Hi @itaibh as you're using a manual release, it's really hard to tell what was done.

At first glance:

- There are no new release of the plugin since 2021: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/applitools-eyes/ 

- It looks like you were able to successfully deploy a snapshot: https://repo.jenkins-ci.org/snapshots/org/jenkins-ci/plugins/applitools-eyes/ so that explains why you had a successfull build + deploy.

=> But as per https://www.jenkins.io/doc/developer/publishing/releasing-manually/#performing-the-release you need to "prepare and perform" the release in order to have Maven:

- Setting the proper version `1.14` (instead of `1.14-SNAPSHOT`) at first sight
- Deploying the released version to https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/applitools-eyes/ (instead of https://repo.jenkins-ci.org/**snapshots**/org/jenkins-ci/plugins/applitools-eyes/ )
- Pushing the tag `1.14` to GitHub (requires https://www.jenkins.io/doc/developer/publishing/releasing-manually/#set-up-github-to-accept-your-ssh-key, but strongly suggested)


=> Then the automatic Update Center process will be able to pick your release and then deploy it to the update center (if everything is set up properly).


Alternative is using the CD process (I saw you started a PR, it might be a matter of time for reviewers to merge it to fully enable it : in that case sorry for the delay)

**Comment by itaibh** [comment]
what about the `<changelist>-SNAPSHOT</changelist>` tag? should I remove it? change it to something else?

**Comment by dduportal** [comment]
> what about the `<changelist>-SNAPSHOT</changelist>` tag? should I remove it? change it to something else?

I have no idea what this markup is used for, you reached my maximum level of Maven skills :D 

I suggest you to start a discussion thread in community.jenkins.io as we are slowly drifting away from the scope of the Jenkins infrastructure.
Please keep the issue here open, no problem to close it only when it's solved "end to end".

**Comment by itaibh** [comment]
I've made some changes to the POM file and now I get 403 when deploying.

**Comment by itaibh** [comment]
I can see the plugin in https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/applitools-eyes/1.14/ but not in https://plugins.jenkins.io/applitools-eyes/ 
Where should I push the tag?

**Comment by dduportal** [comment]
> I've made some changes to the POM file and now I get 403 when deploying.

403 can be when missing permissions (but the account `applitools` looks properly configured in Artifactory), OR it could also be when trying to override a release, which is forbidden, but can happen if you partially deployed the release (mvn only pushed the pom but not the jar). In these cases you have to cut a new release

**Comment by dduportal** [comment]
@itaibh looks like everything is fine:

- The release 1.14 of the plugin is visible in the "Available Plugins" section of ci.jenkins.io (after checking the latest index):

![Capture d’écran 2023-05-10 à 14 49 45](https://github.com/jenkins-infra/helpdesk/assets/1522731/f7d32a2c-e90b-4f7b-9301-a6ed27bd5cbd)

- The plugins.jenkins.io website is now showing the release:


![Capture d’écran 2023-05-10 à 14 50 01](https://github.com/jenkins-infra/helpdesk/assets/1522731/2ab3d3ff-ba12-4dc3-ad51-f5ecb3c03007)


Is this ok for you?

**Comment by itaibh** [comment]
Yes, thank you for your help.

**Comment by dduportal** [comment]
Thanks for your efforts and for the contribution to the Jenkins ecosystem!

I'm gonna proceed and close this issue. Feel free to reopen, as usual, if you have any other issue.
