### ISSUE TITLE
[ci.jenkins.io] Cannot spawn Linux arm64 VM agents

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3812]
### Service(s)

ci.jenkins.io

### Summary

When trying to spin up a Linux VM agent with an arm64 CPU, ci.jenkins.io fails with the following error in the "Cloud Statistics" section:

```
com.microsoft.azure.vmagent.exceptions.AzureCloudException: Deployment Failed: Microsoft.Compute/virtualMachines:ubuntu-22-arm64-0033b0 - BadRequest - com.azure.resourcemanager.resources.models.StatusMessage@363d2d42
	at com.microsoft.azure.vmagent.exceptions.AzureCloudException.create(AzureCloudException.java:37)
	at com.microsoft.azure.vmagent.AzureVMCloud.createProvisionedAgent(AzureVMCloud.java:569)
	at com.microsoft.azure.vmagent.AzureVMCloud$2.call(AzureVMCloud.java:831)
	at com.microsoft.azure.vmagent.AzureVMCloud$2.call(AzureVMCloud.java:808)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

We have to check different locations to understand the root cause:

- "Cloud Statistics" logs (see above an example)
- Jenkins Logs
- Azure Console

=> Most probably an issue with the "type" of VM (size, disk type, etc.)

### Reproduction steps

Replay an existing pipeline with the following content:

```groovy
node('arm64linux') {
  sh 'mvn -v'
}
```

This pipeline should succeed.

**Comment by dduportal** [comment]
Retried a build, and checked the Azure Console message (Monitor -> Activity Logs -> check Deployment errors).

The error cause is:

```
OS disk of Ephemeral VM with size greater than 100 GB is not allowed for VM size Standard_D4pds_v5 when the DiffDiskPlacement is CacheDisk. Please refer to https://aka.ms/Ephemeral for more details.
```

**Comment by dduportal** [comment]
This error is related to https://github.com/jenkinsci/azure-vm-agents-plugin/issues/349.

As per the Azure VM size chart below, the instance type `Standard_D4pds_v5` should be able to have 150Gb of ephemeral disk:
- https://learn.microsoft.com/en-us/azure/virtual-machines/dpsv5-dpdsv5-series#dpdsv5-series
- `Temp storage (SSD) GiB: 150Gb`

However, it looks like that the DiskPlacement being CacheDisk limits us to 100Gb as the OS image needs 30Gb (Ubuntu) as per https://learn.microsoft.com/en-us/azure/virtual-machines/ephemeral-os-disks#size-requirements


Note: on infra.ci, the `arm64` instances are using managed disk: action item here to also switch to ephemeral disk to avoid paying $$ for disks (but same size constraint)

**Comment by dduportal** [comment]
Update:

- `arm64` machines on ci.jenkins.io starts with 100 Gb specified for the ephemeral disk. A quick, check on datadog did not show exact maximum values but 100 Gb should be fine for all Linux machines: let's change it for all Linux agents.
- (outside the initial scope) We realized that the managed disk of the infra.ci Azure VM agents costs us from 35$ to 50$ monthly: let's switch to ephemeral disks!

Todo:

- Decrease the Linux os disk size to 100 Gb on jenkins-infra/jenkins-infra
- Change the instance sizes on infra.ci
- Check for cert-ci and trusted.ci VM agent sizing

**Comment by dduportal** [comment]
![Capture d’écran 2023-11-14 à 11 25 55](https://github.com/jenkins-infra/helpdesk/assets/1522731/8a1fb218-a972-4572-8359-aec8fdd9376e)
![Capture d’écran 2023-11-14 à 11 26 30](https://github.com/jenkins-infra/helpdesk/assets/1522731/ede2ce32-eecd-4ba7-b863-a2416e5e2af2)
![Capture d’écran 2023-11-14 à 11 31 26](https://github.com/jenkins-infra/helpdesk/assets/1522731/ddad19ff-76f0-4d0c-8b1c-87295ce5a139)


LGTM: we can close!
