### ISSUE TITLE
Failed to load plugin-util-api. UnknownHostException: ftp.belnet.be

### ISSUE THREAD

**Issue by rhiskey** [jenkins-infra/helpdesk#3932]
### Service(s)

plugins.jenkins.io

### Summary

```java
java.net.UnknownHostException: ftp.belnet.be
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:572)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2922)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2831)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1927)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1323)
Caused: java.io.IOException: Failed to load https://updates.jenkins.io/download/plugins/plugin-util-api/3.8.0/plugin-util-api.hpi to /var/lib/jenkins/plugins/plugin-util-api.jpi.tmp
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1334)
Caused: java.io.IOException: Failed to download from https://updates.jenkins.io/download/plugins/plugin-util-api/3.8.0/plugin-util-api.hpi (redirected to: https://ftp.belnet.be/mirror/jenkins/plugins/plugin-util-api/3.8.0/plugin-util-api.hpi)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1368)
	at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1925)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2237)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1899)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:121)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Reproduction steps

1. Update Jenkins to 2.443
2. Install `joda-time-api (2.12.5-5.v5495a_235fedf)`
3. Go to plugins and try to update Plugin Utilities API
from 3.6.0 to 3.8.0

**Comment by rhiskey** [comment]
Accidentally resolved:
Need to manually install plugin  joda-time-api

**Comment by dduportal** [comment]
Hi @rhiskey thanks for opening this issue.

The error `java.net.UnknownHostException: ftp.belnet.be` says there is a DNS issue in your system, which explains why the plugin cannot be downloaded.


We tried the request below on different ISPs (French, Belgium, German, but also from AWS us-east-1 and Azure West US) and the mirrors works as expected with no issues which confirm there is something wrong our you network or system:

```
curl -v https://ftp.belnet.be/mirrors/jenkins/plugins/plugin-util-api/3.8.0/plugin-util-api.hpi -I       
*   Trying 193.190.198.27:443...
* Connected to ftp.belnet.be (193.190.198.27) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: C=BE; ST=Bruxelles-Capitale, R?gion de; O=R?seau T?l?matique Belge de la Recherche (Belnet); CN=ftp.belnet.be
*  start date: Sep 12 00:00:00 2023 GMT
*  expire date: Sep 11 23:59:59 2024 GMT
*  subjectAltName: host "ftp.belnet.be" matched cert's "ftp.belnet.be"
*  issuer: C=NL; O=GEANT Vereniging; CN=GEANT OV ECC CA 4
*  SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://ftp.belnet.be/mirrors/jenkins/plugins/plugin-util-api/3.8.0/plugin-util-api.hpi
* [HTTP/2] [1] [:method: HEAD]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: ftp.belnet.be]
* [HTTP/2] [1] [:path: /mirrors/jenkins/plugins/plugin-util-api/3.8.0/plugin-util-api.hpi]
* [HTTP/2] [1] [user-agent: curl/8.4.0]
* [HTTP/2] [1] [accept: */*]
> HEAD /mirrors/jenkins/plugins/plugin-util-api/3.8.0/plugin-util-api.hpi HTTP/2
> Host: ftp.belnet.be
> User-Agent: curl/8.4.0
> Accept: */*
> 
< HTTP/2 200 
HTTP/2 200 
< server: nginx
server: nginx
< date: Mon, 05 Feb 2024 11:59:44 GMT
date: Mon, 05 Feb 2024 11:59:44 GMT
< content-type: application/octet-stream
content-type: application/octet-stream
< content-length: 447860
content-length: 447860
< last-modified: Sat, 23 Dec 2023 12:23:15 GMT
last-modified: Sat, 23 Dec 2023 12:23:15 GMT
< etag: "6586d133-6d574"
etag: "6586d133-6d574"
< accept-ranges: bytes
accept-ranges: bytes

< 
* Connection #0 to host ftp.belnet.be left intact
```


For info, here are the DNS resolution for this domain name:

```
dig ftp.belnet.be

; <<>> DiG 9.10.6 <<>> ftp.belnet.be
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26451
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;ftp.belnet.be.			IN	A

;; ANSWER SECTION:
ftp.belnet.be.		3020	IN	CNAME	ftp-brudie.belnet.be.
ftp-brudie.belnet.be.	2300	IN	A	193.190.198.27

;; Query time: 37 msec
;; SERVER: 9.9.9.9#53(9.9.9.9)
;; WHEN: Mon Feb 05 13:01:18 CET 2024
;; MSG SIZE  rcvd: 83
```

**Comment by dduportal** [comment]
Hello @rhiskey , any news?

**Comment by rhiskey** [comment]
> Hello @rhiskey , any news?

Will be testing today, asap

**Comment by rhiskey** [comment]
> Hello @rhiskey , any news?

Seems like something blocks connection:

`https://updates.jenkins.io/download/plugins/plugin-util-api/3.8.0/plugin-util-api.hpi%20to%20/var/lib/jenkins/plugins/plugin-util-api.jpi.tmp`

Not Found
The requested URL was not found on this server.

**Comment by rhiskey** [comment]
But ~/manage/pluginManager/ update successfully this plugin. Seems like ok
![image](https://github.com/jenkins-infra/helpdesk/assets/35545041/07312327-0b64-48a9-8855-437dc398825d)

**Comment by lemeurherve** [comment]
> > Hello @rhiskey , any news?
> 
> Seems like something blocks connection:
> 
> `https://updates.jenkins.io/download/plugins/plugin-util-api/3.8.0/plugin-util-api.hpi%20to%20/var/lib/jenkins/plugins/plugin-util-api.jpi.tmp`
> 
> Not Found The requested URL was not found on this server.

Where did you see this URL? The `%20to%20...` part seems suspicious to me.

**Comment by lemeurherve** [comment]
Nevermind, it comes from a copy of the complete line from the log you've put in the issue body.

**Comment by rhiskey** [comment]
> Nevermind, it comes from a copy of the complete line from the log you've put in the issue body.

Yep
