### ISSUE TITLE
(Random ?) 404 pages on ci.jenkins.io

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3944]
### Service(s)

ci.jenkins.io

### Summary

- https://ci.jenkins.io/job/Core/job/jenkins/
- https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/install-latest-debian-package/ (sidebar)

yield a 404. The former prevents core PRs from building. Please update the title as needed if the root cause has been located 😅

**Comment by MarkEWaite** [comment]
System log reports:

```
Caught exception evaluating: job.iconColor.iconName in /job/Core/job/jenkins/. Reason: java.lang.reflect.InvocationTargetException
java.lang.StackOverflowError
	at hudson.model.AbstractItem.getFullName(AbstractItem.java:481)
	at hudson.model.AbstractItem.getFullName(AbstractItem.java:481)
	at hudson.model.AbstractItem.getFullName(AbstractItem.java:481)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun$Owner.<init>(WorkflowRun.java:941)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.asFlowExecutionOwner(WorkflowRun.java:788)
	at org.jenkinsci.plugins.workflow.cps.RunningFlowActions.createFor(RunningFlowActions.java:49)
	at org.jenkinsci.plugins.workflow.cps.RunningFlowActions.createFor(RunningFlowActions.java:42)
	at hudson.model.Actionable.createFor(Actionable.java:115)
	at hudson.model.Actionable.getActions(Actionable.java:140)
	at org.datadog.jenkins.plugins.datadog.model.BuildData.getEnvVars(BuildData.java:263)
	at org.datadog.jenkins.plugins.datadog.model.BuildData.<init>(BuildData.java:147)
	at org.datadog.jenkins.plugins.datadog.logs.DatadogTaskListenerDecorator.<init>(DatadogTaskListenerDecorator.java:49)
	at org.datadog.jenkins.plugins.datadog.logs.DatadogTaskListenerDecorator$Factory.of(DatadogTaskListenerDecorator.java:82)
```

**Comment by MarkEWaite** [comment]
I made the mistake of disabling the datadog plugin without removing its configuration from the configuration as code definition.  That break the startup of ci.jenkins.io .  So sorry!

**Comment by lemeurherve** [comment]
Restored ci.jenkins.io with these commands from an ssh session:
```console
cd /var/lib/jenkins/plugins
rm datadog.jpi.disabled
systemctl restart docker-jenkins
```

**Comment by lemeurherve** [comment]
We've got ongoing issues with Datadog, cf #3934

I won't have time to work on this issue tonight, we'll see tomorrow together whether we remove the plugin and its config or not.

**Comment by lemeurherve** [comment]
Updating ci.jenkins.io to the last 6.0.2 version of Datadog plugin resolved the 404 errors on these pages.

cc @nikita-tkachenko-datadog
