### ISSUE TITLE
External user struggling to submit story to stories.jenkins.io

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#4392]
### Service(s)

Other

### Summary

Go to https://stories.jenkins.io/admin/#/collections/user-story

Use netlify CMS to submit a story

Error is 
![image](https://github.com/user-attachments/assets/fc9d57f6-1f43-4fa5-87a7-3759fd38c99c)

Hypothesis is that it works for people who are members of the jenkins-infra org but not people that aren't

**Comment by krisstern** [comment]
We currently have a relevant GSoC 2025 project idea at https://www.jenkins.io/projects/gsoc/2025/project-ideas/revamping-jenkins-io-website-success-stories-feature/. So maybe we can coordinate some effort on this front.

**Comment by dduportal** [comment]
> We currently have a relevant GSoC 2025 project idea at https://www.jenkins.io/projects/gsoc/2025/project-ideas/revamping-jenkins-io-website-success-stories-feature/. So maybe we can coordinate some effort on this front.

Personal opinion: re-implementing the website only because there is a credential issue looks unusual and a waste of effort.
Unless there is something else? I'm having a hard time understanding what is the problem because we are lacking documentation or at least audit trail.

Adding a GSoC project on this "mix" means the focus must be set on documenting rather than (re)implementing otherwise we'll end up in the exact same situation in one year, e.g. it will fix this issue and will create another.

My SRE hat gives me a gut feeling that we are missing documentation only to unblock this particular issue and/or clear specification and problem statement if need to be re-implemented: persona, use cases, etc.

**Comment by krisstern** [comment]
No, the issue is more deep-rooted then simply because there is a credential issue. I don't think the previous maintainer has the capacity (mostly time) to work on the project anymore, or has very limited capacity to check in very rarely once in a while. I was going to take my time and re-work many things on this `stories` project since it looks like at least for now I will be an active (if not the sole) maintainer for it. But I think it may not be a bad idea to add a GSoC project on this mix since having someone else who is not bound by a full-time job like I am may accelerate the changes we will need to make for this feature to keep it functional and relevant. 

IMO, the current workflow deviates much from one that would work well in case we would want to have more transparency (which is preferred for open source I think), especially for the part where people use to submit new stories. I actually just tried it myself and there seemed to have some other issue with the creating new stories as well as the loading of the old records using the link I was provided, even though I did not see the API error. So these signs points to some more tricky issues to be resolved by someone who may or may not respond over the short term (weeks or months) who may or may not know how. (I mean by Gavin Mogan if he will be available, if not then I think that person will be me.)

I would suggest an eventual revamp. But for sure I will need to dig around to see what I can and cannot do at this stage. Let me try and report back shortly.

**Comment by krisstern** [comment]
I was poking around to see if I could add a new user story today, but I am seeing some error output as below at https://stories.jenkins.io/admin/#/collections/user-story:
```console
Error
There's been an error - please [open an issue on GitHub.](https://github.com/netlify/netlify-cms/issues/new?title=TypeError%3A+Cannot+read+properties+of+undefined+%28reading+%27paragraphs%27%29&body=%0A**Describe+the+bug**%0A%0A**To+Reproduce**%0A%0A**Expected+behavior**%0A%0A**Screenshots**%0A%0A**Applicable+Versions%3A**%0A+-+Netlify+CMS+version%3A+%60netlify-cms-app%402.15.72%60%0A+-+Git+provider%3A+%60github%60%0A+-+Browser+version%3A+%60Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_15_7%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F131.0.0.0+Safari%2F537.36%60%0A%0A**CMS+configuration**%0A%60%60%60%0Abackend%3A%0A++name%3A+github%0A++repo%3A+jenkins-infra%2Fstories%0A++branch%3A+main%0A++use_graphql%3A+true%0A++site_domain%3A+stories.jenkins.io%0A++open_authoring%3A+true%0Adisplay_url%3A+https%3A%2F%2Fstories.jenkins.io%0Apublish_mode%3A+editorial_workflow%0Amedia_folder%3A+static%2Fmedia%0Apublic_folder%3A+%2Fmedia%0Acollections%3A%0A++-+name%3A+user-story%0A++++label%3A+User+Stories%0A++++label_singular%3A+User+Story%0A++++extension%3A+yaml%0A++++format%3A+frontmatter%0A++++folder%3A+src%2Fuser-story%0A++++path%3A+%22%7B%7Bpost_name%7D%7D%2Findex%22%0A++++slug%3A+index%0A++++media_folder%3A+%22%22%0A++++public_folder%3A+%22%22%0A++++create%3A+true%0A++++fields%3A%0A++++++-+label%3A+Title%0A++++++++name%3A+title%0A++++++++widget%3A+string%0A++++++-+label%3A+Post+Name+%28slug%29%0A++++++++name%3A+post_name%0A++++++++widget%3A+string%0A++++++-+label%3A+Submitted+By%0A++++++++name%3A+submitted_by%0A++++++++widget%3A+string%0A++++++-+label%3A+Publish+Date%0A++++++++name%3A+date%0A++++++++widget%3A+datetime%0A++++++++date_format%3A+YYYY-MM-DD%0A++++++++time_format%3A+HH%3Amm%3Ass%0A++++++++format%3A+YYYY-MM-DDTHH%3Amm.SSSZ%0A++++++-+label%3A+Tag+Line%0A++++++++name%3A+tag_line%0A++++++++widget%3A+text%0A++++++-+label%3A+Image%0A++++++++name%3A+image%0A++++++++widget%3A+image%0A++++++-+label%3A+Metadata%0A++++++++name%3A+metadata%0A++++++++widget%3A+object%0A++++++++collapsed%3A+false%0A++++++++fields%3A%0A++++++++++-+label%3A+Organization%0A++++++++++++name%3A+organization%0A++++++++++++widget%3A+string%0A++++++++++-+label%3A+Industries%0A++++++++++++name%3A+industries%0A++++++++++++widget%3A+list%0A++++++++++-+label%3A+Programming+Languages%0A++++++++++++name%3A+programming_languages%0A++++++++++++widget%3A+list%0A++++++++++-+label%3A+Platforms%0A++++++++++++name%3A+platforms%0A++++++++++++widget%3A+list%0A++++++++++-+label%3A+Version+Control+Systems%0A++++++++++++name%3A+version_control_systems%0A++++++++++++widget%3A+list%0A++++++++++-+label%3A+Build+Tools%0A++++++++++++name%3A+build_tools%0A++++++++++++widget%3A+list%0A++++++++++-+label%3A+Community+Supports%0A++++++++++++name%3A+community_supports%0A++++++++++++widget%3A+list%0A++++++-+label%3A+Testimonals%0A++++++++name%3A+quotes%0A++++++++widget%3A+list%0A++++++++collapsed%3A+true%0A++++++++fields%3A%0A++++++++++-+label%3A+From%0A++++++++++++name%3A+from%0A++++++++++++type%3A+string%0A++++++++++-+label%3A+Content%0A++++++++++++name%3A+content%0A++++++++++++type%3A+text%0A++++++++++-+label%3A+Image%0A++++++++++++name%3A+image%0A++++++++++++widget%3A+image%0A++++++-+label%3A+Map+Data%0A++++++++name%3A+map%0A++++++++widget%3A+object%0A++++++++collapsed%3A+true%0A++++++++fields%3A%0A++++++++++-+label%3A+Author%0A++++++++++++name%3A+name%0A++++++++++++widget%3A+string%0A++++++++++-+label%3A+Location%0A++++++++++++name%3A+location%0A++++++++++++widget%3A+string%0A++++++++++-+label%3A+Latitude%0A++++++++++++name%3A+latitude%0A++++++++++++widget%3A+number%0A++++++++++++value_type%3A+float%0A++++++++++++min%3A+-90%0A++++++++++++max%3A+90%0A++++++++++-+label%3A+Longitude%0A++++++++++++name%3A+longitude%0A++++++++++++widget%3A+number%0A++++++++++++value_type%3A+float%0A++++++++++++min%3A+-180%0A++++++++++++max%3A+180%0A++++++-+label%3A+Body%0A++++++++name%3A+body_content%0A++++++++widget%3A+object%0A++++++++collapsed%3A+false%0A++++++++fields%3A%0A++++++++++-+label%3A+Title%0A++++++++++++name%3A+title%0A++++++++++++widget%3A+string%0A++++++++++-+label%3A+Paragaphs%0A++++++++++++name%3A+paragraphs%0A++++++++++++widget%3A+list%0A++++++++++++allow_add%3A+true%0A++++++++++++field%3A%0A++++++++++++++label%3A+Body%0A++++++++++++++name%3A+paragraph%0A++++++++++++++widget%3A+markdown%0A++++publish%3A+true%0A++++type%3A+folder_based_collection%0A++++sortable_fields%3A%0A++++++-+commit_date%0A++++++-+title%0A++++++-+date%0A++++++-+commit_author%0A++++view_filters%3A+%5B%5D%0A++++view_groups%3A+%5B%5D%0Aslug%3A%0A++encoding%3A+unicode%0A++clean_accents%3A+false%0A++sanitize_replacement%3A+%22-%22%0AisFetching%3A+false%0Aerror%3A+null%0A%0A%60%60%60%0A%0A**Additional+context**%0A&labels=type%3A+bug)

Opening an issue pre-populates it with the error message and debugging data.
Please verify the information is correct and remove sensitive data if exists.

Details
TypeError: Cannot read properties of undefined (reading 'paragraphs') at /admin/cms.js:2:271858 at Le (/admin/react-dom.production.min.js:100:3) at Pj (/admin/react-dom.production.min.js:231:183) at di (/admin/react-dom.production.min.js:168:305) at Nj (/admin/react-dom.production.min.js:168:236) at sc (/admin/react-dom.production.min.js:168:96) at gf (/admin/react-dom.production.min.js:162:109) at /admin/react-dom.production.min.js:73:230 at unstable_runWithPriority (/admin/react.production.min.js:24:26) at Za (/admin/react-dom.production.min.js:73:8)
```

<img width="1431" alt="Image" src="https://github.com/user-attachments/assets/66313a9b-62e6-4036-9bb5-3aa66ca9b15a" />

**Comment by krisstern** [comment]
Pinging @halkeye to see if there is a quick fix to this issue

**Comment by halkeye** [comment]
I'm really not sure that CMS thingie ever worked?

**Comment by krisstern** [comment]
I see, so we may be better off open a ticket to have the instructions revised then?

**Comment by halkeye** [comment]
No idea. I don't remember ever suggesting it gets used for real. I think I remember realizing that the CMS only worked, when it worked, if you had write access

**Comment by krisstern** [comment]
Okay, I see! Let me double check and make the changes in the documentation accordingly.

**Comment by krisstern** [comment]
We will be fixing this issue up likely during GSoC 2025 this summer

**Comment by Ehtesham-Zahid** [comment]
> We will be fixing this issue up likely during GSoC 2025 this summer

Hi @krisstern, I'm also applying for this project for GSoC. I'm really excited about the opportunity and the value it brings to the community. I’d love to work under your mentorship if selected. Even if I don’t make it, I still plan to contribute during the summer, as the project genuinely aligns with my interests and that’s when I’ll have more time as a student. Looking forward to learning from the process!

**Comment by revanthm1902** [comment]
I've reproduced this on the live admin site (stories.jenkins.io). I'm looking into the preview template logic to see if a null check can fix this. I'd love to take this up!

**Comment by prathamjani** [comment]
Hello, please review my PR. Thanks!
